### ISSUE TITLE
Converting Faster RCNN from caffe to caffe2

### ISSUE THREAD

**Issue by Feynman27** [facebookarchive/caffe2#1101]
Has anyone had success converting faster r-cnn from caffe to caffe2? Blindly running `caffe_translator` gives me the error:

```bash
(caffe2) thomasbalestri@company02:~/PycharmProjects/caffe2$ python -m caffe2.python.caffe_translator ~/VGG16_faster_rcnn_final_train_old.prototxt ~/VGG16_faster_rcnn_final_old.caffemodel
Traceback (most recent call last):
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/thomasbalestri/PycharmProjects/caffe2/build/caffe2/python/caffe_translator.py", line 707, in <module>
    open(input_proto, 'r').read(), caffenet
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 481, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 535, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 568, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 583, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 684, in _MergeField
    merger(tokenizer, message, field)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 773, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/thomasbalestri/anaconda3/envs/caffe2/lib/python2.7/site-packages/google/protobuf/text_format.py", line 652, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 470:3 : Message type "caffe.LayerParameter" has no field named "smooth_l1_loss_param".
```

Maybe I need to write my own custom operator?

**Comment by mynameischaos** [comment]
I have a similar problem.
