### ISSUE TITLE
resnet50_trainer

### ISSUE THREAD

**Issue by liyemei** [facebookarchive/caffe2#1108]
Traceback (most recent call last):

  File "<ipython-input-1-09ef51c5f75a>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/resnet50_trainer.py', wdir='C:/Users/Administrator/Desktop')

  File "C:\Program Files\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 471, in <module>
    main()

  File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 467, in main
    Train(args)

  File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 319, in Train
    cpu_device=args.use_cpu,

  File "D:\caffe2-master\build\caffe2\python\data_parallel_model.py", line 165, in Parallelize
    input_builder_fun(model_helper_obj)

  File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 307, in add_image_input
    img_size=args.image_size,

  File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 68, in AddImageInput
    mirror=0

  File "D:\caffe2-master\build\caffe2\python\brew.py", line 98, in scope_wrapper
    return func(*args, **new_kwargs)

  File "D:\caffe2-master\build\caffe2\python\helpers\tools.py", line 19, in image_input
    outputs = model.net.ImageInput(

  File "D:\caffe2-master\build\caffe2\python\core.py", line 1958, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'

AttributeError: Method ImageInput is not a registered operator. Did you mean: []
&
AttributeError: Method FloatToHalf is not a registered operator. Did you mean: []

**Comment by pietern** [comment]
It looks like this is a build problem, as the operators the trainer attempts to use are not registered. Can you confirm compilation succeeds for you? Which commit are you using?

**Comment by liyemei** [comment]
@pietern yes,I had compiled caffe2  successfully.

**Comment by pietern** [comment]
@liyemei Which commit are you using? Have you retried with master?

**Comment by RailWar** [comment]
I have same problem. I have compiled caffe2 from branch "master" for Windows 10 x64 with GPU.  VS2015
Need reassemle caffe2 with OpenCV.

**Comment by pietern** [comment]
No activity on this issue, closing.

**Comment by WormCoder** [comment]
> Traceback (most recent call last):
> 
> File "", line 1, in 
> runfile('C:/Users/Administrator/Desktop/resnet50_trainer.py', wdir='C:/Users/Administrator/Desktop')
> 
> File "C:\Program Files\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
> execfile(filename, namespace)
> 
> File "C:\Program Files\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
> exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
> File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 471, in 
> main()
> 
> File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 467, in main
> Train(args)
> 
> File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 319, in Train
> cpu_device=args.use_cpu,
> 
> File "D:\caffe2-master\build\caffe2\python\data_parallel_model.py", line 165, in Parallelize
> input_builder_fun(model_helper_obj)
> 
> File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 307, in add_image_input
> img_size=args.image_size,
> 
> File "C:/Users/Administrator/Desktop/resnet50_trainer.py", line 68, in AddImageInput
> mirror=0
> 
> File "D:\caffe2-master\build\caffe2\python\brew.py", line 98, in scope_wrapper
> return func(*args, **new_kwargs)
> 
> File "D:\caffe2-master\build\caffe2\python\helpers\tools.py", line 19, in image_input
> outputs = model.net.ImageInput(
> 
> File "D:\caffe2-master\build\caffe2\python\core.py", line 1958, in **getattr**
> ",".join(workspace.C.nearby_opnames(op_type)) + ']'
> 
> AttributeError: Method ImageInput is not a registered operator. Did you mean: []
> &
> AttributeError: Method FloatToHalf is not a registered operator. Did you mean: []

I have the same problem. Did you solve it?
