### ISSUE TITLE
Where is the documentation for brew helper functions?

### ISSUE THREAD

**Issue by jwatte** [facebookarchive/caffe2#1128]
I'm trying to go through the "multi-GPU training" example, after having built from source on Ubuntu 17 with CUDA 8 on x86_64.

The example uses the older `model_helper functions`. However, it appears that some of the functions it expects to be there, aren't anymore (I run into trouble on AddWeightDecay())

Looking through the online documentation, I find that we're now supposed to use `brew` to make models. That's fine. I also find a list of the function names implemented in `brew` and that's fine, too. But, when I click a function name, I'm taken to the reference for the operator in question. For example, the function `add_image_input` links to the `ImageInput` operator. But, the mapping between the `add_image_input` function and the actual parameters for the `ImageInput` operator is not documented anywhere I can find.

Problem 1: How can I find the documentation for the mapping from `brew` function to actual operator parameters?

Trying to help myself, I trust the built-in Python help, which will surely work here, right? Else, why aren't we using a strict statically typed language to get it right?

    >>> brew.image_input
    <function image_input at 0x7f7ac32ae668>

So far, so good!

    >>> help(brew.image_input)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site.py", line 461, in __call__
        return pydoc.help(*args, **kwds)
      File "/usr/lib/python2.7/pydoc.py", line 1798, in __call__
        self.help(request)
      File "/usr/lib/python2.7/pydoc.py", line 1845, in help
        else: doc(request, 'Help on %s:')
      File "/usr/lib/python2.7/pydoc.py", line 1582, in doc
        pager(render_doc(thing, title, forceload))
      File "/usr/lib/python2.7/pydoc.py", line 1562, in render_doc
        desc += ' in module ' + module.__name__
      File "/usr/local/caffe2/python/brew.py", line 73, in __getattr__
        "registered.".format(helper_name)
    AttributeError: Helper function __name__ not registered.

So there's no help documentation for these functions? Why is that? Maybe I can just call it, and get some information about parameter names?

    >>> brew.image_input(train_model, 'input')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/caffe2/python/brew.py", line 100, in scope_wrapper
        return func(*args, **new_kwargs)
    TypeError: image_input() takes at least 3 arguments (3 given)

At this point, it's actively unhelpful! Not only is it telling me I need to pass in 3 arguments instead of the 3 I gave it (WTH!?) but it also doesn't say anything about the names of the arguments to help me along.

Problem 2: How can I get in-language help for the brew helper functions?

**Comment by charles-r-earp** [comment]
I share your frustration. brew.py is a a nice wrapper around several different modules, with the same interface. image_imput is defined here: https://github.com/caffe2/caffe2/blob/master/caffe2/python/helpers/tools.py

It looks like you need an output blob.
