### ISSUE TITLE
Tutorial Multi-GPU_Training.ipynb is broken (Uses AddWeightDecay)

### ISSUE THREAD

**Issue by jwatte** [facebookarchive/caffe2#1196]
The tutorial for multi-GPU training is broken, because it defines a function that calls AddWeightDecay() on modelhelper, but that function doesn't exist (any more?)
The operators catalog also have no weight decay operator, so it's not obvious what's supposed to happen there instead.

`RuntimeError: Method AddWeightDecay is not a registered operator. Did you mean: []`

    def add_parameter_update_ops(model):
        model.AddWeightDecay(weight_decay)
        ...

The description talks explicitly about AddWeightDecay and Iter being important parts of ModelHelper, yet the implementation doesn't mention these at all:
`https://github.com/caffe2/caffe2/blob/master/caffe2/python/model_helper.py`

**Comment by zpzyt66** [comment]
do you get this question's answer? i meet same problem

**Comment by xieydd** [comment]
I meet same problem,has someone help me?
`
WARNING:root:You are creating an op that the ModelHelper does not recognize: ImageInput.
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "<stdin>", line 2, in add_parameter_update_ops
  File "/opt/caffe2/caffe2/python/model_helper.py", line 470, in __getattr__
    ','.join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method AddWeightDecay is not a registered operator. Did you mean: []
`

**Comment by SteveCruz** [comment]
You can add weight decay by using brew (https://caffe2.ai/docs/brew.html):

```
brew.add_weight_decay(
     model,
     weight_decay
  )
```

Or, alternatively, you can use the implemented caffe2 optimizers and just specify the weight decay value:

https://github.com/caffe2/caffe2/blob/master/caffe2/python/optimizer.py

You can check out the newer tutorial on CIFAR-10 to see how one can use this:

https://github.com/caffe2/tutorials/blob/master/CIFAR10_Part1.ipynb

**Comment by xieydd** [comment]
That`s useful.
