### ISSUE TITLE
AttributeError: Method ImageInput is not a registered operator. Did you mean: []

### ISSUE THREAD

**Issue by Sampson1107** [facebookarchive/caffe2#1212]
I install Caffe2 on the Centos7.1 OS successful.
[root@dl3 build]# python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success
 python -m caffe2.python.operator_test.relu_op_test
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([[[[-0.63784701,  0.91697848,  0.79409802,  0.66860247]],

        [[-0.1668209 ,  0.48904067,  0.99884295,  0.454514  ]],
......
Ran 1 test in 2.305s

OK

while I run the example resnet50_trainer.py, the problem is following:
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
Traceback (most recent call last):
  File "/usr/local/caffe2/python/examples/resnet50_trainer.py", line 528, in <module>
    main()
  File "/usr/local/caffe2/python/examples/resnet50_trainer.py", line 524, in main
    Train(args)
  File "/usr/local/caffe2/python/examples/resnet50_trainer.py", line 364, in Train
    cpu_device=args.use_cpu,
  File "/usr/local/caffe2/python/data_parallel_model.py", line 169, in Parallelize
    input_builder_fun(model_helper_obj)
  File "/usr/local/caffe2/python/examples/resnet50_trainer.py", line 342, in add_image_input
    dtype=args.dtype,
  File "/usr/local/caffe2/python/examples/resnet50_trainer.py", line 64, in AddImageInput
    mirror=1
  File "/usr/local/caffe2/python/brew.py", line 101, in scope_wrapper
    return func(*args, **new_kwargs)
  File "/usr/local/caffe2/python/helpers/tools.py", line 16, in image_input
    outputs = model.net.ImageInput(blob_in, blob_out, **kwargs)
  File "/usr/local/caffe2/python/core.py", line 1975, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method ImageInput is not a registered operator. Did you mean: []

I replace the commit to Caffe2-master, 0.7 ,0.8. All the commits are the same problem. Any method to solve the problem? Thanks a lot!

**Comment by nlaptev** [comment]
Hello @Sampson1107 , You need to compile Caffe2 with opencv to fix this.

**Comment by WormCoder** [comment]
> Hello @Sampson1107 , You need to compile Caffe2 with opencv to fix this.

Caffe2 is in pytorch now. I have installed pytorch. 
Did I need to recompile caffe2 to use caffe2?

**Comment by orionr** [comment]
@WormCoder you are right - PyTorch and Caffe2 have merged and now use the same build and install system. However, PyTorch by default doesn't use OpenCV or ffmpeg. In order to use operators that require those (including the one above) you'll need to install those libraries and then compile from source with

```
# Install OpenCV and ffmpeg first via apt-get, conda, etc.
cd <pytorch/pytorch checkout location>
USE_OPENCV=1 USE_FFMPEG=1 python setup.py install
```

You can also confirm in the setup.py output that OpenCV and ffmpeg were found.

Hope that helps.

**Comment by WormCoder** [comment]
> @WormCoder you are right - PyTorch and Caffe2 have merged and now use the same build and install system. However, PyTorch by default doesn't use OpenCV or ffmpeg. In order to use operators that require those (including the one above) you'll need to install those libraries and then compile from source with
> 
> ```
> # Install OpenCV and ffmpeg first via apt-get, conda, etc.
> cd <pytorch/pytorch checkout location>
> USE_OPENCV=1 USE_FFMPEG=1 python setup.py install
> ```
> You can also confirm in the setup.py output that OpenCV and ffmpeg were found.
> 
> Hope that helps.

that helps. Thanks a lot.
