### ISSUE TITLE
Does Caffe2 really use GPU when run a model translated from caffe?

### ISSUE THREAD

**Issue by ZIWEILI** [facebookarchive/caffe2#1229]
Hi, 
I met some problems when I did tiny-yolo detection in different platform. Firstly, I  run tiny-yolo  on the original darknet. Then, I used  [caffe-yolo](https://github.com/Banus/caffe-yolo) to convert it to Caffe. Finally, I use caffe_translator.py to convert Caffe model of tiny-yolo to Caffe2 model. My CPU chip is intel i7 and GPU is GTX970.

I found that,  

With darknet, it costs 1.563 seconds per image in CPU mode, and only 0.003 seconds in GPU mode.

With caffe, it costs  0.471 seconds per image in CPU mode, and only 0.041 seconds in GPU mode.

Obviously, it can be seen that the speed of using GPU is much faster than CPU mode in darknet and Caffe.

However, when I test tiny-yolo in Caffe2 on two different hardware platform (one has GPU device, and the other doesn't have. Since Caffe2 detects hardware automatically and I cannot manually choose mode I wanna use ), both of them costs about 0.25 seconds.

When I opened the NVIDIA X Server to see the GPU Utilization, I found that,  in darknet GPU mode, the GPU Utilization can reach 30%, and in caffe and caffe2 GPU mode, the GPU Utilization can only reach 10%.  

Since the speed of Caffe GPU mode is 10 times faster than CPU mode, it can be proved that GPU really did work. But in Caffe2, the speed of CPU mode and GPU mode are almost same, and  GPU Utilization is very low.

I doubt that,  did the GPU really work when I ran a Caffe2 model converted from Caffe? Why there is no difference in speed when I ran CPU and GPU mode in Caffe2?

Thanks a lot for your help!

**Comment by diz-vara** [comment]
Caffe2 works with GPU - but not in workspace.Predictor framework.
You must use older way to setup/invoke your networks.

Example YOLO net from your post showed me for 3 fullHD images 4.6 seconds in CPU mode - and 0.05 seconds in CUDA mode:
~~~~
a=np.random.rand(2,3,1080,1920).astype(np.float32)

workspace.ResetWorkspace();
#device_opts = core.DeviceOption(caffe2_pb2.CPU, 0)
device_opts = core.DeviceOption(caffe2_pb2.CUDA, 0)

init_def = caffe2_pb2.NetDef()
with open("exec_net.pb", 'rb') as f:
    init_def.ParseFromString(f.read())
    init_def.device_option.CopyFrom(device_opts)
    workspace.RunNetOnce(init_def.SerializeToString())

net_def = caffe2_pb2.NetDef()
with open("predict_net.pb", 'rb') as f:
    net_def.ParseFromString(f.read())
    net_def.device_option.CopyFrom(device_opts)
    workspace.CreateNet(net_def.SerializeToString())

name = net_def.name
out_name = net_def.external_output[-1];
in_name = net_def.external_input[0]



#%%
workspace.FeedBlob(in_name, a, device_opts)
print ('Running net..."' + name + '"' )

tic = time.time()
workspace.RunNet(name, 1)
results = workspace.FetchBlob(out_name)
tm = time.time() - tic
print (tm)
~~~~

**Comment by rohith14** [comment]
Hi diz-vara,

I tried your approach and ran into couple of issues.  Any idea what might be the issue ?

# Error1 : 
## Code
with open("predict_net.pb", 'rb') as f:
net_def.ParseFromString(f.read())
    net_def.device_option.CopyFrom(device_opts)
    workspace.CreateNet(net_def.SerializeToString())

## Error
Required modules imported.
BATCH SIZE:  1
Config set!
Functions set.
Mean was set to:  128
INIT_NET =  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb
PREDICT_NET =  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
found  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb ...now looking for  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
all needed files found! loading the model in the next block
Number of batches:  1000
Pre-processing images...
Done pre-processing, initializing net...
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1004 16:05:53.260538 10063 workspace.cc:157] Blob data not in the workspace.
Traceback (most recent call last):
  File "alexnet_pretrain.py", line 202, in <module>
    workspace.CreateNet(net_def.SerializeToString())
  File "/local/caffe2/build/caffe2/python/workspace.py", line 167, in CreateNet
    StringifyProto(net), overwrite,
  File "/local/caffe2/build/caffe2/python/workspace.py", line 190, in CallWithExceptionIntercept
    print("Traceback for operator {} in network {}".format(op_id, net_name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 164: ordinal not in range(128)

# Error2
## Code
When i changed the code to
with open("predict_net.pb", 'rb') as f:
    net_def.ParseFromString(f.read())
    net_def.device_option.CopyFrom(device_opts)
    workspace.CreateNet(net_def)

## Error
Required modules imported.
BATCH SIZE:  1
Config set!
Functions set.
Mean was set to:  128
INIT_NET =  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb
PREDICT_NET =  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
found  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb ...now looking for  /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
all needed files found! loading the model in the next block
Number of batches:  1000
Pre-processing images...
Done pre-processing, initializing net...
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1004 16:13:15.168926 17579 workspace.cc:157] Blob data not in the workspace.
Traceback for operator 1886221678 in network bvlc_alexnet
Traceback (most recent call last):
  File "alexnet_pretrain.py", line 203, in <module>
    workspace.CreateNet(net_def)
  File "/local/caffe2/build/caffe2/python/workspace.py", line 167, in CreateNet
    StringifyProto(net), overwrite,
  File "/local/caffe2/build/caffe2/python/workspace.py", line 186, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:52] blob != nullptr. op Conv: Encountered a non-existing input blob: data

**Comment by zhangwei147258** [comment]
@diz-vara   I see " YOLO net from your post showed me for 3 fullHD images 4.6 seconds in CPU mode - and 0.05 seconds in CUDA mode "  ,how do you translator YOLO model from caffe to  init_net.pb and predict_net.pb in caffe2 ? Refer to your method above，i find  gpu mode costs much longer time than cpu mode ?  I don't know what the problem is，can you help me ?Thanks!

**Comment by zhangw864680355** [comment]
@ZIWEILI  can you use tiny-yolo model to test picture and recognize something in caffe2 ? I successfully recognize the content in caffe ,but fail to do it in caffe2. I find the data of detections = workspace.FetchBlob(out_name) are different from  out = net.forward_all(data=np.asarray([transformer.preprocess('data', img)])),  what is wrong ???

**Comment by gemfield** [comment]
> Hi diz-vara,
> 
> I tried your approach and ran into couple of issues. Any idea what might be the issue ?
> 
> # Error1 :
> ## Code
> with open("predict_net.pb", 'rb') as f:
> net_def.ParseFromString(f.read())
> net_def.device_option.CopyFrom(device_opts)
> workspace.CreateNet(net_def.SerializeToString())
> 
> ## Error
> Required modules imported.
> BATCH SIZE: 1
> Config set!
> Functions set.
> Mean was set to: 128
> INIT_NET = /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb
> PREDICT_NET = /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
> found /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb ...now looking for /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
> all needed files found! loading the model in the next block
> Number of batches: 1000
> Pre-processing images...
> Done pre-processing, initializing net...
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> W1004 16:05:53.260538 10063 workspace.cc:157] Blob data not in the workspace.
> Traceback (most recent call last):
> File "alexnet_pretrain.py", line 202, in 
> workspace.CreateNet(net_def.SerializeToString())
> File "/local/caffe2/build/caffe2/python/workspace.py", line 167, in CreateNet
> StringifyProto(net), overwrite,
> File "/local/caffe2/build/caffe2/python/workspace.py", line 190, in CallWithExceptionIntercept
> print("Traceback for operator {} in network {}".format(op_id, net_name))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 164: ordinal not in range(128)
> 
> # Error2
> ## Code
> When i changed the code to
> with open("predict_net.pb", 'rb') as f:
> net_def.ParseFromString(f.read())
> net_def.device_option.CopyFrom(device_opts)
> workspace.CreateNet(net_def)
> 
> ## Error
> Required modules imported.
> BATCH SIZE: 1
> Config set!
> Functions set.
> Mean was set to: 128
> INIT_NET = /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb
> PREDICT_NET = /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
> found /local/caffe2/build/caffe2/python/models/bvlc_alexnet/init_net.pb ...now looking for /local/caffe2/build/caffe2/python/models/bvlc_alexnet/predict_net.pb
> all needed files found! loading the model in the next block
> Number of batches: 1000
> Pre-processing images...
> Done pre-processing, initializing net...
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> W1004 16:13:15.168926 17579 workspace.cc:157] Blob data not in the workspace.
> Traceback for operator 1886221678 in network bvlc_alexnet
> Traceback (most recent call last):
> File "alexnet_pretrain.py", line 203, in 
> workspace.CreateNet(net_def)
> File "/local/caffe2/build/caffe2/python/workspace.py", line 167, in CreateNet
> StringifyProto(net), overwrite,
> File "/local/caffe2/build/caffe2/python/workspace.py", line 186, in CallWithExceptionIntercept
> return func(*args, **kwargs)
> RuntimeError: [enforce fail at operator.cc:52] blob != nullptr. op Conv: Encountered a non-existing input blob: data

You need feed data blob to current workspace, or you can create ConstantFill operator (to output data blob during model initial) and save it to init_net. Check https://zhuanlan.zhihu.com/p/45067948 for more detail.
