### ISSUE TITLE
Successfully built but failed in test on windows (CPU only)

### ISSUE THREAD

**Issue by lkywd** [facebookarchive/caffe2#1353]
I was trying to build caffe2 on windows 10 by visual studio 2017 (CPU only). I set ”-DBUILD_PYTHON=ON” in "build_windows.bat" and ran it. I got "Caffe2 built successfully" finally and can find "caffe2_pybind11_state.pyd" in "{BUILD_ROOT}\build\caffe2\python". I have set ”PYTHONPATH” to "{BUILD_ROOT}\build" and can successfully import "core" and "workspace" from "caffe2.python". But when I ran "python -m caffe2.python.operator_test.relu_op_test", it failed and returned:

"Cannot create operator of type 'Relu' on the device 'CPU'. Verify that implementation for the corresponding device exist."

Here is the full message:

>python -m caffe2.python.operator_test.relu_op_test
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Caffe2 build configuration:
  BLAS                      : Eigen
  BUILD_TYPE                : Release
  CXX_FLAGS                 : /DWIN32 /D_WINDOWS /W3 /GR /EHsc -openmp /MP /bigobj
  FORCE_FALLBACK_CUDA_MPI   :
  GIT_VERSION               : v0.8.1-519-gcbe0848-dirty
  HAS_MKL_DNN               :
  HAS_MKL_SGEMM_PACK        :
  PERF_WITH_AVX             :
  PERF_WITH_AVX2            :
  UNIQUE_LONG_TYPEMETA      : 1
  USE_ACCELERATE            :
  USE_ATEN                  : OFF
  USE_CUDA                  : OFF
  USE_EIGEN_FOR_BLAS        : 1
  USE_GFLAGS                : OFF
  USE_GLOG                  : OFF
  USE_GLOO                  :
  USE_LITE_PROTO            :
  USE_MKL                   :
  USE_MPI                   : OFF
  USE_NCCL                  : OFF
  USE_NNPACK                : OFF
  USE_NVTX                  :
  USE_OPENMP                : ON
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(1, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(60, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(5, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(30, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(20, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(16, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(64, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(3, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(24, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(135, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([ 0.], dtype=float32), gc=, dc=[], engine=u'')
[E D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:126] Cannot find operator schema for Relu. Will skip schema checking.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 727, in evaluate_test_data
    collector=self.collector
  File "C:\Python27\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 140, in run
    return test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 34, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 605, in timed_test
    result = test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 41, in test_relu
    self.assertDeviceChecks(dc, op, [X], [0])
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\hypothesis_test_util.py", line 354, in assertDeviceChecks
    dc.CheckSimple(op, inputs, outputs_to_check, input_device_options)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\device_checker.py", line 60, in CheckSimple
    workspace.RunOperatorOnce(op)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\workspace.py", line 173, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:182] op. Cannot create operator of type 'Relu' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "X" output: "Y" name: "" type: "Relu" device_option { } engine: ""

Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([ 0.], dtype=float32), gc=, dc=[], engine=u'')
[E D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:126] Cannot find operator schema for Relu. Will skip schema checking.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 727, in evaluate_test_data
    collector=self.collector
  File "C:\Python27\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 140, in run
    return test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 34, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 605, in timed_test
    result = test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 41, in test_relu
    self.assertDeviceChecks(dc, op, [X], [0])
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\hypothesis_test_util.py", line 354, in assertDeviceChecks
    dc.CheckSimple(op, inputs, outputs_to_check, input_device_options)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\device_checker.py", line 60, in CheckSimple
    workspace.RunOperatorOnce(op)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\workspace.py", line 173, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:182] op. Cannot create operator of type 'Relu' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "X" output: "Y" name: "" type: "Relu" device_option { } engine: ""

Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([ 0.], dtype=float32), gc=, dc=[], engine=u'')
[E D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:126] Cannot find operator schema for Relu. Will skip schema checking.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 727, in evaluate_test_data
    collector=self.collector
  File "C:\Python27\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 140, in run
    return test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 34, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 605, in timed_test
    result = test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 41, in test_relu
    self.assertDeviceChecks(dc, op, [X], [0])
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\hypothesis_test_util.py", line 354, in assertDeviceChecks
    dc.CheckSimple(op, inputs, outputs_to_check, input_device_options)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\device_checker.py", line 60, in CheckSimple
    workspace.RunOperatorOnce(op)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\workspace.py", line 173, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:182] op. Cannot create operator of type 'Relu' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "X" output: "Y" name: "" type: "Relu" device_option { } engine: ""

C:\Python27\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full(2, True) will return an array of dtype('bool')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)
Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([ 0.,  0.], dtype=float32), gc=, dc=[], engine=u'')
[E D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:126] Cannot find operator schema for Relu. Will skip schema checking.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 727, in evaluate_test_data
    collector=self.collector
  File "C:\Python27\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 140, in run
    return test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 34, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 605, in timed_test
    result = test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 41, in test_relu
    self.assertDeviceChecks(dc, op, [X], [0])
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\hypothesis_test_util.py", line 354, in assertDeviceChecks
    dc.CheckSimple(op, inputs, outputs_to_check, input_device_options)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\device_checker.py", line 60, in CheckSimple
    workspace.RunOperatorOnce(op)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\workspace.py", line 173, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:182] op. Cannot create operator of type 'Relu' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "X" output: "Y" name: "" type: "Relu" device_option { } engine: ""

Falsifying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([ 0.], dtype=float32), gc=, dc=[], engine=u'')
[E D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:126] Cannot find operator schema for Relu. Will skip schema checking.
You can add @seed(115312674691109174884899229750452384568) to this test to reproduce this failure.
E
======================================================================
ERROR: test_relu (__main__.TestRelu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 34, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 1019, in wrapped_test
    state.run()
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 857, in run
    print_example=True, is_final=True
  File "C:\Python27\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 136, in run
    return test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 34, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "C:\Python27\lib\site-packages\hypothesis\core.py", line 605, in timed_test
    result = test(*args, **kwargs)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\operator_test\relu_op_test.py", line 41, in test_relu
    self.assertDeviceChecks(dc, op, [X], [0])
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\hypothesis_test_util.py", line 354, in assertDeviceChecks
    dc.CheckSimple(op, inputs, outputs_to_check, input_device_options)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\device_checker.py", line 60, in CheckSimple
    workspace.RunOperatorOnce(op)
  File "D:\Caffe2Ins\caffe2\build\caffe2\python\workspace.py", line 173, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at D:\Caffe2Ins\caffe2\caffe2\core\operator.cc:182] op. Cannot create operator of type 'Relu' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "X" output: "Y" name: "" type: "Relu" device_option { } engine: ""

----------------------------------------------------------------------
Ran 1 test in 0.094s

FAILED (errors=1)

How could I solve these problems? Thanks!

**Comment by Yangqing** [comment]
This might be due to a visual studio bug - updating to the most recent visual studio version might fix the issue. For a related issue see #1644.
