### ISSUE TITLE
Optional dependencies failed

### ISSUE THREAD

**Issue by YangBain** [facebookarchive/caffe2#1423]
When I run :
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
sudo pip install \
      flask \
      future \
      graphviz \
      hypothesis \
      jupyter \
      matplotlib \
      pydot python-nvd3 \
      pyyaml \
      requests \
      scikit-image \
      scipy \
      setuptools \
      six \
      tornado
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I got the following error:

Downloading/unpacking enum34 (from hypothesis)
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking coverage (from hypothesis)
  Downloading coverage-4.4.1.tar.gz (369kB): 369kB downloaded
  Running setup.py (path:/tmp/pip_build_root/coverage/setup.py) egg_info for package coverage
    
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
Downloading/unpacking ipywidgets (from jupyter)
  Downloading ipywidgets-7.0.3-py2.py3-none-any.whl (68kB): 68kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'widgetsnbextension ~=3.0.0', 'at', ' ~=3.0.0')

Storing debug log for failure in /home/beans/.pip/pip.log

For this problem, anyone who can give me some suggestions?  Thank you very much.

**Comment by pietern** [comment]
This is a problem with the installation of ipywidgets, not Caffe2.

We are working on getting continuous testing for our notebooks as well as our code.

Closing this issue, since there is nothing I can do about it.
