### ISSUE TITLE
resnet50_trainer.py + OpenMPI failing with unhandled type error

### ISSUE THREAD

**Issue by kramimus** [facebookarchive/caffe2#1441]
Running resnet50_trainer.py with OpenMPI (just over TCP) across 2 nodes on the master branch and hitting this error:

```
$ mpirun.openmpi -machinefile $HOME/machinefile.gpu -npernode 1 python resnet50_trainer.py --train_data null
/usr/bin/ssh: /program/caffe2/0.8.2dev-9.0-7.0-py27/env/lib/libcrypto.so.1.0.0: no version information available (required by /usr/bin/ssh)
/usr/bin/ssh: /program/caffe2/0.8.2dev-9.0-7.0-py27/env/lib/libcrypto.so.1.0.0: no version information available (required by /usr/bin/ssh)
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
Caffe2 build configuration: 
  BLAS                      : Eigen
  BUILD_TYPE                : Release
  CXX_FLAGS                 :  -fopenmp -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing
  FORCE_FALLBACK_CUDA_MPI   : 1
  GIT_VERSION               : v0.8.1-600-gbd025ea
  HAS_MKL_DNN               : 
  HAS_MKL_SGEMM_PACK        : 
  PERF_WITH_AVX             : 1
  PERF_WITH_AVX2            : 1
  UNIQUE_LONG_TYPEMETA      : 
  USE_ACCELERATE            : 
  USE_ATEN                  : OFF
  USE_CUDA                  : ON
  USE_EIGEN_FOR_BLAS        : 1
  USE_GFLAGS                : ON
  USE_GLOG                  : OFF
  USE_GLOO                  : 
  USE_LITE_PROTO            : 
  USE_MKL                   : 
  USE_MPI                   : ON
  USE_NCCL                  : ON
  USE_NNPACK                : ON
  USE_NVTX                  : 
  USE_OPENMP                : ON
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Adding gradient operators
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
Caffe2 build configuration: 
  BLAS                      : Eigen
  BUILD_TYPE                : Release
  CXX_FLAGS                 :  -fopenmp -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing
  FORCE_FALLBACK_CUDA_MPI   : 1
  GIT_VERSION               : v0.8.1-600-gbd025ea
  HAS_MKL_DNN               : 
  HAS_MKL_SGEMM_PACK        : 
  PERF_WITH_AVX             : 1
  PERF_WITH_AVX2            : 1
  UNIQUE_LONG_TYPEMETA      : 
  USE_ACCELERATE            : 
  USE_ATEN                  : OFF
  USE_CUDA                  : ON
  USE_EIGEN_FOR_BLAS        : 1
  USE_GFLAGS                : ON
  USE_GLOG                  : OFF
  USE_GLOO                  : 
  USE_LITE_PROTO            : 
  USE_MKL                   : 
  USE_MPI                   : ON
  USE_NCCL                  : ON
  USE_NNPACK                : ON
  USE_NVTX                  : 
  USE_OPENMP                : ON
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Add initial parameter sync
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.02237200737 secs
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0224199295044 secs
--------------------------------------------------------------------------
[[21030,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: ip-10-23-35-42

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
Traceback for operator 1212 in network resnet50_init
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:1051
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:1060
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:964
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:323
resnet50_trainer.py:433
resnet50_trainer.py:595
resnet50_trainer.py:599
Traceback (most recent call last):
  File "resnet50_trainer.py", line 599, in <module>
    main()
  File "resnet50_trainer.py", line 595, in main
    Train(args)
  File "resnet50_trainer.py", line 436, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/workspace.py", line 206, in RunNetOnce
    StringifyProto(net),
  File "/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/workspace.py", line 189, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at broadcast_ops_gpu.cc:38] false. Unhandled type: int Error from operator: 
input: "broadcast_0_cw" input: "gpu_0/label" output: "gpu_0/label" name: "label" type: "Broadcast" arg { name: "status_blob" s: "broadcast_label_status" } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO" control_input: "gpu_0/data"
Traceback for operator 1212 in network resnet50_init
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:1051
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:1060
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:964
/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/data_parallel_model.py:323
resnet50_trainer.py:433
resnet50_trainer.py:595
resnet50_trainer.py:599
Traceback (most recent call last):
  File "resnet50_trainer.py", line 599, in <module>
    main()
  File "resnet50_trainer.py", line 595, in main
    Train(args)
  File "resnet50_trainer.py", line 436, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/workspace.py", line 206, in RunNetOnce
    StringifyProto(net),
  File "/program/caffe2/0.8.2dev-9.0-7.0-py27/caffe2/build/caffe2/python/workspace.py", line 189, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at broadcast_ops_gpu.cc:38] false. Unhandled type: int Error from operator: 
input: "broadcast_0_cw" input: "gpu_0/label" output: "gpu_0/label" name: "label" type: "Broadcast" arg { name: "status_blob" s: "broadcast_label_status" } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO" control_input: "gpu_0/data"
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.openmpi detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[21030,1],1]
  Exit code:    1
--------------------------------------------------------------------------
[ip-10-23-35-42:10889] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
[ip-10-23-35-42:10889] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```

Running on the master branch and single node resnet50_trainer.py runs fine on the same caffe2 install.

Using OpenMPI 1.10 package included in Ubuntu 16.04.

**Comment by pietern** [comment]
This should be fixed now that #1537 is merged.
