### ISSUE TITLE
bi-directional encoder in seq2seq translation mode example fails to get created

### ISSUE THREAD

**Issue by fmetze** [facebookarchive/caffe2#1517]
I am getting the following error when trying to build a bi-directional encoder for the seq2seq translation example. If I am not using the bi-directional encoder, things seem to work, I can turn on attention, train on 2 GPUs, etc - and I am getting recognizable results, but I'd like to try the bidirectional encoder.

This is on an Azure Ubuntu 16.04 Deep Learning VM, with CUDNN 6.0, using the current (as of now) master branch.

metze@DeepUbuntu:~/caffe2-install/caffe2/python/examples$ python2 ../models/seq2seq/train.py --source-corpus /home/metze/training/news-commentary-v8.es-en.es --target-corpus /home/metze/training/news-commentary-v8.es-en.en --source-corpus-eval /home/metze/dev/newstest2009.es --target-corpus-eval /home/metze/dev/newstest2009.en --use-bidirectional-encoder
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Source vocab size 7211
Target vocab size 6877
Number of training batches 5436
Number of eval batches 79
Initializing Seq2SeqModelCaffe2 from scratch: Start
Traceback (most recent call last):
  File "../models/seq2seq/train.py", line 784, in <module>
    main()
  File "../models/seq2seq/train.py", line 779, in main
    max_gradient_norm=args.max_gradient_norm,
  File "../models/seq2seq/train.py", line 667, in run_seq2seq_model
    model_obj.initialize_from_scratch()
  File "../models/seq2seq/train.py", line 518, in initialize_from_scratch
    self._build_model(init_params=True)
  File "../models/seq2seq/train.py", line 129, in _build_model
    loss_blobs = self.model_build_fun(model)
  File "../models/seq2seq/train.py", line 251, in model_build_fun
    num_gpus=self.num_gpus,
  File "/home/metze/caffe2-install/caffe2/python/models/seq2seq/seq2seq_util.py", line 314, in build_embedding_encoder
    scope=get_layer_scope(scope, 'encoder', i),
  File "/home/metze/caffe2-install/caffe2/python/models/seq2seq/seq2seq_util.py", line 161, in rnn_bidirectional_layer
    scope=(scope + '/' if scope else '') + 'fw',
  File "/home/metze/caffe2-install/caffe2/python/models/seq2seq/seq2seq_util.py", line 133, in rnn_unidirectional_layer
    outputs_with_grads=outputs_with_grads,
  File "/home/metze/caffe2-install/caffe2/python/rnn_cell.py", line 86, in apply_over_sequence
    preprocessed_inputs = self.prepare_input(model, inputs)
  File "/home/metze/caffe2-install/caffe2/python/rnn_cell.py", line 329, in prepare_input
    axis=2,
  File "/home/metze/caffe2-install/caffe2/python/brew.py", line 116, in scope_wrapper
    return func(*args, **new_kwargs)
  File "/home/metze/caffe2-install/caffe2/python/helpers/fc.py", line 73, in fc
    return _FC_or_packed_FC(model, model.net.FC, *args, **kwargs)
  File "/home/metze/caffe2-install/caffe2/python/helpers/fc.py", line 52, in _FC_or_packed_FC
    tags=ParameterTags.WEIGHT
  File "/home/metze/caffe2-install/caffe2/python/model_helper.py", line 228, in create_param
    shape=shape,
  File "/home/metze/caffe2-install/caffe2/python/modeling/initializers.py", line 45, in create_param
    [], param_name, shape=shape, **self.operator_kwargs)
  File "/home/metze/caffe2-install/caffe2/python/core.py", line 2041, in <lambda>
    op_type, *args, **kwargs)
  File "/home/metze/caffe2-install/caffe2/python/core.py", line 2018, in _CreateAndAddToSelf
    op = CreateOperator(op_type, inputs, outputs, **kwargs)
  File "/home/metze/caffe2-install/caffe2/python/core.py", line 355, in CreateOperator
    operator.arg.add().CopyFrom(utils.MakeArgument(key, value))
  File "/home/metze/caffe2-install/caffe2/python/utils.py", line 165, in MakeArgument
    key, value, type(value), set(type(v) for v in value)
ValueError: Unknown iterable argument type: key=shape value=[1024.0, 256], value type=<type 'list'>[set([<type 'float'>, <type 'int'>])]

**Comment by fmetze** [comment]
#1541 fixes
