### ISSUE TITLE
run python -m caffe2.python.operator_test.relu_op_test error

### ISSUE THREAD

**Issue by xiaobogaga** [facebookarchive/caffe2#1534]
successfully build caffe2 in centos, but when run with

> python -m caffe2.python.operator_test.relu_op_test

it shows error with following:

`
Traceback (most recent call last):
`
`
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
`
`    
"__main__", fname, loader, pkg_name)
`
`
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
`
`   exec code in run_globals
`
` File "/root/software_repos/caffe2/caffe2/build/caffe2/python/operator_test/relu_op_test.py", line 22, in <module>
`
`
from hypothesis import given
`
` File "/usr/lib/python2.7/site-packages/hypothesis/__init__.py", line 31, in <module> 
`
`   from hypothesis.core import given, find, example, seed
`
`
 File "/usr/lib/python2.7/site-packages/hypothesis/core.py", line 31, in <module>
`
`   
from coverage.files import canonical_filename
`
`
ImportError: cannot import name canonical_filename
`

it seems like python package <b>hypothesis</b> raise the error, But I don't know why, can anybody help me, thanks...

server info:
cuda 8.0
python: 2.7
centos: 7

**Comment by xiaobogaga** [comment]
it's solved by update coverage package.
