### ISSUE TITLE
run resnet50_trainer.py error in distributed mode with cannot create operator of type RedisStoreHandlerCreate

### ISSUE THREAD

**Issue by xiaobogaga** [facebookarchive/caffe2#1550]
build success and the simple test pass. but when I try **resnet50_trainer.py** in **distributed mode** with following command:

```
resnet50_trainer.py \
               --train_data ~mnist/mnist-train-nchw-lmdb/  \
               --test_data  ~mnist/mnist-test-nchw-lmdb/   \
               --base_learning_rate 0.0001  \
               --redis_host ip \
               --redis_port 7777 \ 
               --run_id 0 \
               --num_shards 2
```

it shows <b>error</b> like:

```
E1201 11:19:53.120268 16708 operator.cc:125] Cannot find operator schema  for 
    RedisStoreHandlerCreate. Will skip schema checking.
Traceback (most recent call last):
File "/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 609, in 
<module>
    main()
File "/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 605, in main
    Train(args)
File "/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 311, in Train
    prefix=args.run_id,
File "/root/caffe2/caffe2/caffe2/build/caffe2/python/workspace.py", line 180, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at operator.cc:181] op. 
Cannot create operator of type 'RedisStoreHandlerCreate' on the device 'CPU'. 
Verify that implementation for the corresponding device exist. 
It might also happen if the binary is not linked with the operator implementation code. 
If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. 
Operator def: output: 
      "store_handler" name: "" 
      type: "RedisStoreHandlerCreate" 
      arg { name: "host" s: "ip" } 
      arg { name: "prefix" s: "0" } 
      arg { name: "port" i: 7777 } 
```

the redis server is started with `redis-server --port`, the error message seems to provide solution, but I don't understand, anybody can help me?

platform information:
* centos
* gcc 4.8.5
* redis 3.2.2
* python 2.7.5

**Comment by landscape-ooo** [comment]
@xiaobogaga  hi-redis is not install  ? 
- pls check like this 

```
cd caff2_install_path 
 find -name *.so |xargs ldd  |grep redis 
```
- if not install ,you can do like this 

-- 1,  install depdence
`yum install hiredis-devel 
`
if other linux .pls google  install hi-redis hi-redis-devel 
-- 2, cmake  caffe2 ,add -DUSE_REDIS=ON 
-- 3, check

**Comment by xiaobogaga** [comment]
yes, thank you for your solution, it has solve my problem.
