### ISSUE TITLE
multi host multi GPU in Distributed mode  ,run resnet50_trainer.py  get RuntimeError 

### ISSUE THREAD

**Issue by gjpicker** [facebookarchive/caffe2#1553]
- build config 
```
>>>cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
>>>uname -a 
Linux xxx 3.18.6-2.el7.centos.x86_64 #1 SMP Mon Oct 24 13:01:33 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
>>> nvidia-smi  
Tesla K40m  10GB 
>>> python 
Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2

```
```
OpenCV_DIR=/home/username/workspace/opencv/ /home/username/workspace/cmake/bin/cmake -DCUB_INCLUDE_DIR=/usr/local/cub/ \
 -DOpenCV_DIR=/home/username/workspace/opencv/  \
 -DCMAKE_INSTALL_PREFIX=/home/username/workspace/caffe2_conda_3/ \
 -DMPI_C_COMPILER=/home/username/workspace/openmpi/bin/mpicc \
 -DUSE_REDIS=ON \
 -DUSE_GLOO=ON -DUSE_OPENMP=ON -DUSE_MPI=ON -DUSE_OPENCV=ON  ..

```
>>>
[configure.log](https://github.com/caffe2/caffe2/files/1521165/configure.log)

- resnet50_trainer.py revision 
>>>[7facfa4a841cb78a40267701b813d0286a267cbd](https://github.com/caffe2/caffe2/commit/7facfa4a841cb78a40267701b813d0286a267cbd)

=  1. run  with gloo
=
*  * [host1]
>>>python  resnet50_trainer.py  --train_data dataset/cifar10_train_lmdb  --test_data  dataset/cifar10_test_lmdb --gpus 0,1,2,3  --batch_size 128  --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2  --shard_id 0 --run_id 50012 --redis_host 192.168.58.213

* * [host2]
>>>python  resnet50_trainer.py  --train_data dataset/cifar10_train_lmdb  --test_data  dataset/cifar10_test_lmdb --gpus 0,1,2,3  --batch_size 128  --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2  --shard_id 0 --run_id 50013 --redis_host 192.168.58.213

* *  both host1 host 2 ,get error 

```

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
INFO:resnet50_trainer:Using epoch size: 49920
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E1201 17:43:44.068279  4063 operator.cc:461] Shape inference error: [enforce fail at conv_pool_op_base.h:554] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E1201 17:43:44.068775  4063 operator.cc:462] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E1201 17:43:44.068804  4063 operator.cc:463] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0419700145721 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0436420440674 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0416529178619 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0416789054871 secs
E1201 17:44:19.353432  4063 common_world_ops.h:126] Caught store handler timeout exception: [/home/username/download/caffe2_new_3/caffe2/distributed/redis_store_handler.cc:126] Wait timeout for name(s): allreduce_0_cw_op/1
E1201 17:44:19.356403  4063 net_simple.cc:75] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "timeout_ms" i: 30000 } arg { name: "rank" i: 0 } arg { name: "interface" s: "" } arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "transport" s: "tcp" } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
E1201 17:44:19.356473  4063 net.h:70] Failed to execute async run
E1201 17:44:19.356497  4063 workspace.cc:309] Error when running network resnet50_init
Traceback for operator 1069 in network resnet50_init
/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py:1768
/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py:1232
/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py:1283
/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py:1300
/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py:1148
/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py:271
resnet50_trainer.py:453
resnet50_trainer.py:631
resnet50_trainer.py:635
Traceback (most recent call last):
  File "resnet50_trainer.py", line 635, in <module>
    main()
  File "resnet50_trainer.py", line 631, in main
    Train(args)
  File "resnet50_trainer.py", line 468, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/home/username/workspace/caffe2_conda_3/caffe2/python/workspace.py", line 210, in RunNetOnce
    StringifyProto(net),
  File "/home/username/workspace/caffe2_conda_3/caffe2/python/workspace.py", line 193, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1017] gWorkspace->RunNetOnce(def).  
```

=  2. run  with MPI
=

* * python cmdB  [host1]
>>> /home/username/workspace/openmpi/bin/mpirun --verbose -n 2 -x PATH   -x LD_LIBRARY_PATH -x PYTHONPATH  --host  192.168.9.197,192.168.9.56 \
python  resnet50_trainer.py  --train_data dataset/cifar10_train_lmdb  --test_data  dataset/cifar10_test_lmdb --gpus 0,1,2,3  --batch_size 128  --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2   --run_id 50002 --redis_host 192.168.58.213

* * mpi error output [host1]
```

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
INFO:resnet50_trainer:Using epoch size: 49920
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
INFO:resnet50_trainer:Using epoch size: 49920
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
Traceback (most recent call last):
  File "resnet50_trainer.py", line 635, in <module>
    main()
  File "resnet50_trainer.py", line 631, in main
    Train(args)
  File "resnet50_trainer.py", line 466, in Train
    data_parallel_model.OptimizeGradientMemory(train_model, {}, set(), False)
  File "/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py", line 1686, in OptimizeGradientMemory
    input_shapes_all_devices,
  File "/home/username/workspace/caffe2_conda_3/caffe2/python/workspace.py", line 255, in InferShapesAndTypes
    net_protos, blob_dimensions
RuntimeError: [enforce fail at operator.cc:482] . Invalid shape inference for operator Broadcast Expected 4 outputs, but got 1 
INFO:data_parallel_model:Add initial parameter sync
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
Traceback (most recent call last):
  File "resnet50_trainer.py", line 623, in <module>
    main()
  File "resnet50_trainer.py", line 619, in main
    Train(args)
  File "resnet50_trainer.py", line 456, in Train
    data_parallel_model.OptimizeGradientMemory(train_model, {}, set(), False)
  File "/home/username/workspace/caffe2_conda_3/caffe2/python/data_parallel_model.py", line 1686, in OptimizeGradientMemory
    input_shapes_all_devices,
  File "/home/username/workspace/caffe2_conda_3/caffe2/python/workspace.py", line 255, in InferShapesAndTypes
    net_protos, blob_dimensions
RuntimeError: [enforce fail at operator.cc:482] . Invalid shape inference for operator Broadcast Expected 4 outputs, but got 1 
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1094,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

=  3. run  with single host  ,# **success** !
=
>>>python  resnet50_trainer.py  --train_data dataset/cifar10_train_lmdb  --test_data  dataset/cifar10_test_lmdb --gpus 0,1,2,3  --batch_size 128  --num_labels 10 --epoch_size 50000 --num_epochs 10 

```
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
INFO:resnet50_trainer:Using epoch size: 49920
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E1201 18:12:41.491335 12338 operator.cc:461] Shape inference error: [enforce fail at conv_pool_op_base.h:554] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E1201 18:12:41.491978 12338 operator.cc:462] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E1201 18:12:41.492005 12338 operator.cc:463] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0558331012726 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0475769042969 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0461800098419 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.046021938324 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/10
INFO:resnet50_trainer:Finished iteration 1/390 of epoch 0 (17.91 images/sec)
INFO:resnet50_trainer:Training loss: 2.7755279541, accuracy: 0.125
INFO:resnet50_trainer:Finished iteration 2/390 of epoch 0 (174.53 images/sec)
INFO:resnet50_trainer:Training loss: 43.6997413635, accuracy: 0.09375
INFO:resnet50_trainer:Finished iteration 3/390 of epoch 0 (177.90 images/sec)
INFO:resnet50_trainer:Training loss: 27.1067466736, accuracy: 0.0625
INFO:resnet50_trainer:Finished iteration 4/390 of epoch 0 (176.83 images/sec)
INFO:resnet50_trainer:Training loss: 39.7513237, accuracy: 0.03125
INFO:resnet50_trainer:Finished iteration 5/390 of epoch 0 (177.19 images/sec)
INFO:resnet50_trainer:Training loss: 13.1747694016, accuracy: 0.0625
INFO:resnet50_trainer:Finished iteration 6/390 of epoch 0 (176.07 images/sec)
INFO:resnet50_trainer:Training loss: 31.8183822632, accuracy: 0.09375
INFO:resnet50_trainer:Finished iteration 7/390 of epoch 0 (175.46 images/sec)
INFO:resnet50_trainer:Training loss: 20.7837562561, accuracy: 0.03125
INFO:resnet50_trainer:Finished iteration 8/390 of epoch 0 (176.11 images/sec)
```

=  summary 
=
- with distributed mode ,always get error . however in single mode ,run sucess  . is anyone help me ?

**Comment by xiaobogaga** [comment]
**same error** happend when run distributed mode using redis with command:

machine 1:

```
python ~/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py 
--train_data /root/caffe2/caffe2_notebooks/tutorial_data/mnist/mnist-train-nchw-lmdb/  
--test_data /root/caffe2/caffe2_notebooks/tutorial_data/mnist/mnist-test-nchw-lmdb/  
--base_learning_rate 0.0001  --batch_size 2 --num_epochs 20 --redis_host $ip 
--redis_port $port --run_id 0001 --num_shards 2
```

machine 2(only cpu):

```
~/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py 
--train_data /root/caffe2_examples_data/mnist/mnist-train-nchw-lmdb/  
--test_data /root/caffe2_examples_data/mnist/mnist-test-nchw-lmdb/  
--base_learning_rate 0.0001  --batch_size 2 --num_epochs 20 --redis_host $ip
--redis_port $port --run_id 0004 --num_shards 2 --use_cpu true
```

error infor:

```
common_world_ops.h:126] Caught store handler timeout exception: 
[/root/caffe2/caffe2/caffe2/caffe2/distributed/redis_store_handler.cc:126] Wait timeout 
for name(s) allreduce_0_cw_op/1 E1201 18:57:26.106040 19152 net_simple.cc:75] 
Operator failed: input: 
"store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: 
"CreateCommonWorld" 
arg { name: "timeout_ms" i: 30000 } arg { name: "rank" i: 0 } arg { name: "interface" s: "" } 
arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "transport" s: "tcp" } 
arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
E1201 18:57:26.106102 19152 net.h:70] Failed to execute async run
E1201 18:57:26.106120 19152 workspace.cc:309] Error when running network resnet50_init
Traceback for operator 268 in network resnet50_init
/root/caffe2/caffe2/caffe2/build/caffe2/python/data_parallel_model.py:1768
/root/caffe2/caffe2/caffe2/build/caffe2/python/data_parallel_model.py:1232
/root/caffe2/caffe2/caffe2/build/caffe2/python/data_parallel_model.py:1283
/root/caffe2/caffe2/caffe2/build/caffe2/python/data_parallel_model.py:1300
/root/caffe2/caffe2/caffe2/build/caffe2/python/data_parallel_model.py:1148
/root/caffe2/caffe2/caffe2/build/caffe2/python/data_parallel_model.py:271
/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py:443
/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py:605
/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py:609
Traceback (most recent call last):
  File "/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 609, 
in <module>
    main()
  File "/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 605, 
in main
    Train(args)
  File "/root/caffe2/caffe2/caffe2/caffe2/python/examples/resnet50_trainer.py", line 446, 
in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/root/caffe2/caffe2/caffe2/build/caffe2/python/workspace.py", line 210, in RunNetOnce
    StringifyProto(net),
  File "/root/caffe2/caffe2/caffe2/build/caffe2/python/workspace.py", line 193, in 
CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1005] gWorkspace->RunNetOnce(def).  

```

**Comment by landscape-ooo** [comment]
I have same error in distributed mode 

`python resnet50_trainer.py --train_data cifar10_train_lmdb --test_data  cifar10_test_lmdb --gpus 0,1  --num_shards 4 --shard_id 0 --run_id 10000 --redis_host 127.0.0.1`

```
Traceback (most recent call last):
  File “/home/work/examples/resnet50_trainer.py", line 609, 
in <module>
    main()
  File "/home/work/examples/resnet50_trainer.py", line 605, 
in main
    Train(args)
  File "/home/work/examples/resnet50_trainer.py", line 446, 
in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File “/home/work/caffe_bin/caffe2/python/workspace.py", line 210, in RunNetOnce
    StringifyProto(net),
  File "/home/work/caffe_bin/caffe2/python/workspace.py", line 193, in 
CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1005] gWorkspace->RunNetOnce(def).


```

**Comment by jianjiangg** [comment]
+1 
python resnet50_trainer.py --train_data train_lmdb --gpus 0,1,2,3,4  --num_shards 3 --run_id 20171203110411 --redis_host 10.3.255.201


```

Traceback (most recent call last):
  File “./resnet50_trainer.py", line 609, 
in <module>
    main()
  File “./resnet50_trainer.py", line 605, 
in main
    Train(args)
  File “./resnet50_trainer.py", line 446, 
in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File “/usr/local/caffe2/python/workspace.py", line 210, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/caffe2/python/workspace.py", line 193, in 
CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:1005] gWorkspace->RunNetOnce(def).

```

**Comment by gjpicker** [comment]
yes ,I had mistaken python command  ,sorry 

eg , right command is 



[host1]
`
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/work/workspace/caffe2_conda_3/lib/  PYTHONPATH=/home/work/workspace/caffe2_conda_3/  /home/work/workspace/caffe2_install/bin/python   resnet50_trainer.py --train_data dataset/cifar10_train_lmdb --test_data dataset/cifar10_test_lmdb --gpus 0,1,2,3 --batch_size 128 --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2 --shard_id 1 --run_id 50090 --redis_host 10.38.9.197
`


[host2]
`
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/work/workspace/caffe2_conda_3/lib/  PYTHONPATH=/home/work/workspace/caffe2_conda_3/  /home/work/workspace/caffe2_install/bin/python   resnet50_trainer.py --train_data dataset/cifar10_train_lmdb --test_data dataset/cifar10_test_lmdb --gpus 0,1,2,3 --batch_size 128 --num_labels 10 --epoch_size 50000 --num_epochs 10 --num_shards 2 --shard_id 0 --run_id 50090 --redis_host 10.38.9.197
`

> **# pls carefull . run_id should same as each other**


logger in success

```
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0, 1, 2, 3]
INFO:resnet50_trainer:Using epoch size: 49920
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E1205 18:43:04.973498 25265 operator.cc:461] Shape inference error: [enforce fail at conv_pool_op_base.h:554] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E1205 18:43:04.974012 25265 operator.cc:462] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E1205 18:43:04.974045 25265 operator.cc:463] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0588238239288 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0448079109192 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0434889793396 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0432651042938 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/10
INFO:resnet50_trainer:Finished iteration 1/195 of epoch 0 (17.86 images/sec)
INFO:resnet50_trainer:Training loss: 2.69027018547, accuracy: 0.0625
INFO:resnet50_trainer:Finished iteration 2/195 of epoch 0 (169.04 images/sec)
INFO:resnet50_trainer:Training loss: 32.2851028442, accuracy: 0.09375
INFO:resnet50_trainer:Finished iteration 3/195 of epoch 0 (178.49 images/sec)
INFO:resnet50_trainer:Training loss: 38.9879150391, accuracy: 0.25
INFO:resnet50_trainer:Finished iteration 4/195 of epoch 0 (179.29 images/sec)
INFO:resnet50_trainer:Training loss: 36.2279014587, accuracy: 0.09375
INFO:resnet50_trainer:Finished iteration 5/195 of epoch 0 (178.55 images/sec)
INFO:resnet50_trainer:Training loss: 16.4774494171, accuracy: 0.03125
INFO:resnet50_trainer:Finished iteration 6/195 of epoch 0 (178.52 images/sec)
INFO:resnet50_trainer:Training loss: 31.8828353882, accuracy: 0.1875
INFO:resnet50_trainer:Finished iteration 7/195 of epoch 0 (178.46 images/sec)
.....

```

**Comment by pietern** [comment]
It looks like in all cases the run ID was different between participating nodes. It should be the same.

**Comment by Tron-x** [comment]
你好，请问你是怎么解决mpirun 那个错误的，我跟你用mpi那个错误一模一样。

**Comment by gjpicker** [comment]
this issue was located in user_level mistaken ,it doesn't associated to any caffe2's issue 

= = =  = = =  = = =  = = =  
ask:你好，请问你是怎么解决mpirun 那个错误的，我跟你用mpi那个错误一模一样。
ans: 不同mpi命令，要保证相同run_id
比如：
 host1
 ```
mpirun   -n 2  --host 192.168.9.197,192.168.9.56 
python resnet50_trainer.py --train_data dataset/cifar10_train_lmdb .........  --num_shards 2 --run_id 50002  ......
```
host2
```
mpirun   -n 2  --host 192.168.9.197,192.168.9.56 
python resnet50_trainer.py --train_data dataset/cifar10_train_lmdb .........  --num_shards 2 --run_id 50002  ......
```

请见谅，因为提出问题较早，有点忘记具体命令了。
= = =  = = =  = = =  = = =  


- - -
ask:Hello, how do you solve the error of mpirun, I am exactly the same as you used mpi. (google_translastor)
 ans:with different command_line of mpi hosts ,Your guarantee should have same run_id between them
- - -
