### ISSUE TITLE
db_. Cannot open db

### ISSUE THREAD

**Issue by Abhinesh88** [facebookarchive/caffe2#1575]
Unable to read lmdb database from the example as well as my own code.

`python lmdb_create_example.py --output_file test_abhi`

Error :
```
>>> Write database...
Inserted 0 rows
Inserted 16 rows
Inserted 32 rows
Inserted 48 rows
Inserted 64 rows
Inserted 80 rows
Inserted 96 rows
Inserted 112 rows
Checksum/write: 1746832
>>> Read database...
Traceback for operator 0 in network lmdbtest_init
/usr/local/caffe2/python/model_helper.py:450
lmdb_create_example.py:86
lmdb_create_example.py:118
lmdb_create_example.py:122
Traceback (most recent call last):
  File "lmdb_create_example.py", line 122, in <module>
    main()
  File "lmdb_create_example.py", line 118, in main
    read_db_with_caffe2(args.output_file, checksum)
  File "lmdb_create_example.py", line 90, in read_db_with_caffe2
    workspace.RunNetOnce(model.param_init_net)
  File "/usr/local/caffe2/python/workspace.py", line 210, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/caffe2/python/workspace.py", line 193, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at db.h:206] db_. Cannot open db: test_abhi of type lmdb Error from operator: 
output: "dbreader_test_abhi" name: "" type: "CreateDB" arg { name: "db_type" s: "lmdb" } arg { name: "db" s: "test_abhi" }
```
Environment:
Ubuntu 14.04.1
cuda 8.0.61
cudnn 6.0.21
python 2.7.6

**Comment by lowding** [comment]
The same question I met;Database  was created successfully, but failed to open when reading it;
The main  source code of  lmdb_create_example.py   is : 
` checksum = create_db(args.output_file)   **# we can see database is created successfully** 
#For testing reading:
 read_db_with_caffe2(args.output_file, checksum)  **# but reading failed**
`
above all ,could I think that I installed  lmdb correctly  though some errors occur ?
