### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HealthCheck'

### ISSUE THREAD

**Issue by panovr** [facebookarchive/caffe2#1784]
After Caffe2 installation, invoke this command:
```
python -m caffe2.python.operator_test.relu_op_test
```
will get this error message:
```
python -m caffe2.python.operator_test.relu_op_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ylzhao/develop/caffe2/build/caffe2/python/operator_test/relu_op_test.py", line 24, in <module>
    import caffe2.python.hypothesis_test_util as hu
  File "/home/ylzhao/develop/caffe2/build/caffe2/python/hypothesis_test_util.py", line 86, in <module>
    suppress_health_check=[hypothesis.HealthCheck.too_slow],
AttributeError: 'module' object has no attribute 'HealthCheck'

```

**Comment by pjh5** [comment]
This looks like a problem with hypothesis. 

How did you install caffe2? Is this on linux?

**Comment by panovr** [comment]
I install caffe2 from source code on Ubuntu 16.04.

**Comment by panovr** [comment]
The problem was fixed by upgrading hypothesis package.
