### ISSUE TITLE
Failed to translate caffenet model to caffe2 model

### ISSUE THREAD

**Issue by DevilGragon** [facebookarchive/caffe2#1878]
I have followed the example to convert caffemodel to caffe2 model given in the tutorial and success in MNIST and cifar-10 model but failed in CaffeNetmodel.

I used the following command:
python -m caffe2.python.caffe_translator ../caffe2/python/cat_test/deploy.prototxt ../caffe2/python/cat_test/caffenet_cat_gpu_train_iter_450000.caffemodel
and got the following errors

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
INFO:caffe_translator:Translate layer data
INFO:caffe_translator:Translate layer conv1
INFO:caffe_translator:Translate layer relu1
INFO:caffe_translator:Translate layer pool1
INFO:caffe_translator:Translate layer norm1
INFO:caffe_translator:Translate layer conv2
INFO:caffe_translator:Translate layer relu2
INFO:caffe_translator:Translate layer pool2
INFO:caffe_translator:Translate layer norm2
INFO:caffe_translator:Translate layer conv3
INFO:caffe_translator:Translate layer relu3
INFO:caffe_translator:Translate layer conv4
INFO:caffe_translator:Translate layer relu4
INFO:caffe_translator:Translate layer conv5
INFO:caffe_translator:Translate layer relu5
INFO:caffe_translator:Translate layer pool5
INFO:caffe_translator:Translate layer fc6
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gaor/gaor/caffe2/caffe2/build/caffe2/python/caffe_translator.py", line 927, in <module>
    input_dims=args.input_dims
  File "/home/gaor/gaor/caffe2/caffe2/build/caffe2/python/caffe_translator.py", line 299, in TranslateModel
    return TranslatorRegistry.TranslateModel(*args, **kwargs)
  File "/home/gaor/gaor/caffe2/caffe2/build/caffe2/python/caffe_translator.py", line 288, in TranslateModel
    net_params=net_params, input_dims=input_dims)
  File "/home/gaor/gaor/caffe2/caffe2/build/caffe2/python/caffe_translator.py", line 228, in TranslateLayer
    layer, pretrained_blobs, is_test, **kwargs)
  File "/home/gaor/gaor/caffe2/caffe2/build/caffe2/python/caffe_translator.py", line 627, in TranslateInnerProduct
    output + '_w'
  File "caffe2/python/utils.py", line 79, in NumpyArrayToCaffe2Tensor
    tensor.float_data.extend(list(arr.flatten().astype(float)))
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
MemoryError

Could anyone help me, thanks!

**Comment by DevilGragon** [comment]
I solved this problem with exbanding my virtual system memory to 8GB.
