### ISSUE TITLE
Loading model from checkpoint

### ISSUE THREAD

**Issue by MatthewInkawhich** [facebookarchive/caffe2#1908]
My goal is to continue training from a checkpoint lmdb.

I created the checkpoint lmdb using the method shown in the "MNIST - Create a CNN from Scratch" tutorial at https://caffe2.ai/docs/tutorial-MNIST.html:

```
model.Checkpoint([ITER] + model.params, [],
               db="mnist_lenet_checkpoint_%05d.lmdb",
               db_type="lmdb", every=20)
```

Note that `model` in this case is an object of the `model_helper` class. While this usage documentation is useful, there is no example of how to load the model from the checkpoint lmdb to continue training or run inference.

While there is an operator called `Load` in the Operators Catalog, I cannot figure out how to invoke this function. For example, when I try this:

```
train_model = model_helper.ModelHelper(name="mnist_train", arg_scope=arg_scope)
train_model.Load(db=saved_checkpoint, db_type="lmdb",  load_all=1)
```

I get the following error:
```
WARNING:root:You are creating an op that the ModelHelper does not recognize: Load.
Traceback (most recent call last):
  File "continue_training_from_checkpoint.py", line 46, in <module>
    train_model.Load(db=saved_checkpoint, db_type="lmdb",  load_all=1)
  File "/usr/local/caffe2/python/core.py", line 2043, in <lambda>
    op_type, *args, **kwargs)
TypeError: _CreateAndAddToSelf() takes at least 3 arguments (2 given)
```

Note that the ModelHelper does not recognize Load.

Any help would be greatly appreciated.

**Comment by iteal** [comment]
I don't know if it is the best, but this works for me :

```
db_reader = 'reader'
params_for_current_model = model.GetAllParams()

workspace.RunOperatorOnce(
        core.CreateOperator('CreateDB', [], [db_reader], db=path_to_checkpoint_lmdb, db_type='lmdb',
                            device_option=device_option))
workspace.RunOperatorOnce(
        core.CreateOperator('Load', [db_reader], params_for_current_model, load_all=1, strip_prefix="",
                            add_prefix="", device_option=device_option))
logger.info('Model %s is loaded from a checkpoint %s', model.name, path_to_checkpoint_lmdb)
```
