### ISSUE TITLE
Global average pooling fails if the Operator name has "Pool" inside

### ISSUE THREAD

**Issue by rillomas** [facebookarchive/caffe2#1971]
I ran into this issue when I was testing a converted model from ONNX. Since ONNX allows a node to have any name, if a GlobalAveragePool node's name contains the word "Pool", caffe2 checks for a kernel size parameter and fails.

The code which seems to be doing something wrong is here:

https://github.com/caffe2/caffe2/blob/master/caffe2/operators/conv_pool_op_base.h#L167

# Reproducing code
```python
import numpy as np
import os
import shutil
import onnx
import onnx_caffe2.frontend
from caffe2.proto import caffe2_pb2
from caffe2.python import model_helper, workspace, brew, utils

IN_DATA_NAME = "in_data"
OUT_DATA_NAME = "out_data"

model = model_helper.ModelHelper(name="gap_net")
# The following results in an error because the node name has the word "Pool" in it
brew.average_pool(model, IN_DATA_NAME, OUT_DATA_NAME, global_pooling=True, name="PoolPoolPool")
# The following works
#brew.average_pool(model, IN_DATA_NAME, OUT_DATA_NAME, global_pooling=True)

model.param_init_net.UniformFill([], IN_DATA_NAME, shape=(1,3,3,3), min=-2.0, max=2.0)
workspace.RunNetOnce(model.param_init_net)
id = workspace.FetchBlob(IN_DATA_NAME)
print(IN_DATA_NAME, id)
workspace.CreateNet(model.net)
workspace.RunNet(model.net)
b = workspace.FetchBlob(OUT_DATA_NAME)
print(OUT_DATA_NAME, b)
print("out shape", b.shape)
for c in id[0]:
    print(np.mean(c))
```

# Results
## When operator is named "PoolPoolPool"

```
$ python caffe2_bug.py
in_data [[[[-1.4755055   0.8291166   1.8095036 ]
   [-0.772043    0.8637898   1.1757474 ]
   [-0.07659233  0.74965596 -1.4103965 ]]

  [[ 1.4675004  -0.39934552 -1.7228949 ]
   [-1.3966541  -0.40833402 -0.9643401 ]
   [ 1.5508156  -1.6803277   0.6537442 ]]

  [[-0.15532112 -0.2408135  -1.3010323 ]
   [-1.0444076  -0.1672839   0.7210665 ]
   [-0.68532014  1.5852299   1.0893228 ]]]]
Traceback for operator 0 in network gap_net
/usr/local/caffe2/python/helpers/pooling.py:42
/usr/local/caffe2/python/brew.py:119
caffe2_bug.py:14
Traceback (most recent call last):
  File "caffe2_bug.py", line 22, in <module>
    workspace.CreateNet(model.net)
  File "/usr/local/caffe2/python/workspace.py", line 167, in CreateNet
    StringifyProto(net), overwrite,
  File "/usr/local/caffe2/python/workspace.py", line 193, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at conv_pool_op_base.h:176] kernel_[dim]. If you are doing convolution or pooling, you will need to set explicitly the kernel size.
```

## When operator is not named

```
$ python caffe2_bug.py
in_data [[[[ 1.8542964   1.317266    0.935776  ]
   [-1.9163942  -0.15530694  1.7955503 ]
   [-0.70009923  1.8828702  -0.90508103]]

  [[-1.5479324  -0.69316816 -1.8525925 ]
   [ 1.2535133   0.6431527   0.5932145 ]
   [-0.76321626 -1.0862188  -0.8733362 ]]

  [[ 0.8466208  -0.04586458  0.4006784 ]
   [-0.4090197   1.4020386  -0.26248538]
   [-1.9751848   1.8272867  -1.7275488 ]]]]
out_data [[[[ 0.45654202]]

  [[-0.4807315 ]]

  [[ 0.00628013]]]]
out shape (1, 3, 1, 1)
0.4565419
-0.48073155
0.0062801307
```

**Comment by Maratyszcza** [comment]
It seems there are several tangled bug here. The code in `conv_pool_op_base.h` checks for `operator_def.name()` while it should be checking for `operator_def.type()`. We usually name our operators in lowercase, so the code that checks padding and access kernel size never ran. When it does run, it doesn't check if the pooling is global (and thus doesn't need kernel size). cc @Yangqing to decide how to deal with this code.

**Comment by Yangqing** [comment]
Ah this is probably because ConvPoolOpBase is a huge base class that is not that well tested...

We should probably monkey patch it (credit goes to @Maratyszcza ) - by fixing the name() calls to type() calls, and also check that global_pooling_ is not true (in which case we don't check the kernel size).
