### ISSUE TITLE
Errors including std::__cxx11 or [abi:cxx11] or Linux with Anaconda

### ISSUE THREAD

**Issue by pjh5** [facebookarchive/caffe2#1980]
This is an issue to track solutions and updates to these common errors encountered when installing Caffe2 with Anaconda on some Linux distros:

```
undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string
undefined reference to `leveldb::Status::ToString[abi:cxx11]()
Undefined reference to google::protobuf::internal::empty_string_[abi:cxx11]
```

These problems most commonly arise when using Anaconda's versions of protobuf, leveldb, or opencv. 

These are all caused by this https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html . Basically, default Ubuntu ships with gcc 4.8.5 , but a lot of Anaconda libraries have been built with gcc 5+ . Libraries compiled with gcc > 5 are not compatible with those compiled with gcc < 5, due to changes in std::string and std::list; see the earlier link for details. What this means is that you must ensure that all of the libraries that Caffe2 is built against have the same ABI version, either all built with gcc < 5 or all built with gcc > 5. 

If you encounter any of these errors that have [abi:cxx11] or std::__cxx11:: in them, then try one of the following options:

- If you don't need to change Caffe2's source code, then just install our pre-built binary with `conda install -c caffe2 caffe2` (or if you want CUDA, then `conda install -c caffe2 caffe2-cuda9.0-cudnn7`)

If you need to build from source:
- Try adding `-DCMAKE_CXX_FLAGS=-D__GLIBCXX_USE_CXX11_ABI=0` to your `cmake` call. If you are installing with conda-build, then your `cmake` call will be in either `conda/cuda/build.sh` `conda/no_cuda/build.sh`.
- Use system versions of protobuf, opencv, or leveldb (try installing with apt-get). Uninstall these libraries from Anaconda and try to build again.
In both of these cases, remember to delete your build folder to remove any caching effects.

We will work on automatic detection of the gcc ABI version so that we can detect these problems and warn about them before they happen. A solution to allow seamless installs from source on Ubuntu machines with Anaconda packages may be very difficult, and we are open to suggestions.

UPDATE:
There are now gcc4.8 compatible conda packages available. You can install them like
`conda install -c caffe2 caffe2-gcc4.8` or `conda install -c caffe2-cuda9.0-cudnn7-gcc4.8` 
If you want to build Caffe2 from source but still want to use Anaconda and would like to avoid any gcc mismatch problems, then use https://github.com/caffe2/caffe2/blob/master/scripts/build_anaconda.sh , which can help adapt the conda-build process based on your gcc version. 

For example, you can run
`CONDA_INSTALL_LOCALLY=1 scripts/build_anaconda.sh`
to build Caffe2 and install into the current conda environment or 
`CONDA_INSTALL_LOCALLY=1 BUILD_ENVIRONMENT=-cuda- scripts/build_anaconda.sh`
to build Caffe2 with CUDA support and install into the current conda environment.

**Comment by 7oud** [comment]
@pjh5 I installed caffe2 using `conda install -c caffe2 caffe2-cuda8.0-cudnn7`, but failed to import caffe2.
1. conda create -n caffe2
2. conda install -c caffe2 caffe2-cuda8.0-cudnn7
3. python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'

    (caffe2) zoud@i7:~$ python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
    WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: /home/zoud/Prog/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

**Comment by pjh5** [comment]
@7oud can you show me the output of `conda list` and `gcc --version` and `uname -a`? Did you run commands 2 and 3 in the 'caffe2' environment?

**Comment by 7oud** [comment]
1. yes, I run cmd 2 and 3 in 'caffe2' environment.
2. conda list in 'caffe2':

	(caffe2) zoud@i7:~$ conda list
	\# packages in environment at /home/zoud/Prog/anaconda2/envs/caffe2:
	\#
	bzip2                     1.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	caffe2-cuda8.0-cudnn7     0.8.dev          py27hd36ff57_0    caffe2
	cairo                     1.14.12              h77bcde2_0  
	certifi                   2016.2.28                py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	ffmpeg                    3.4                  h7264315_0  
	fontconfig                2.12.4               h88586e7_1  
	freetype                  2.8                  hab7d2ae_1  
	future                    0.16.0                   py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	gflags                    2.2.1                hf484d3e_0  
	glib                      2.53.6               h5d9569c_2  
	glog                      0.3.5                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	graphite2                 1.3.10               hf63cedd_1  
	harfbuzz                  1.7.4                hc5b324e_0  
	hdf5                      1.10.1               h9caa474_1  
	icu                       58.2                 h9c2bf20_1  
	jasper                    1.900.1              hd497a04_4  
	jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	libgcc-ng                 7.2.0                h7cc24e2_2  
	libgfortran-ng            7.2.0                h9f7466a_2  
	libiconv                  1.14                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	libopus                   1.2.1                hb9ed12e_0  
	libpng                    1.6.34               hb9fc6fc_0  
	libprotobuf               3.4.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	libstdcxx-ng              7.2.0                h7a57d05_2  
	libtiff                   4.0.9                h28f6b97_0  
	libvpx                    1.6.1                h888fd40_0  
	libxcb                    1.12                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	libxml2                   2.9.4                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	lmdb                      0.9.21                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	mkl                       2017.0.3                      0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	numpy                     1.13.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	opencv                    3.3.1            py27hdcf4849_0  
	openssl                   1.0.2l                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	pcre                      8.39                          1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	pip                       9.0.1                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	pixman                    0.34.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	protobuf                  3.4.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	python                    2.7.13                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	setuptools                36.4.0                   py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	six                       1.10.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	wheel                     0.29.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	xz                        5.2.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
	zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

3. gcc & linux
(caffe2) zoud@i7:\~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    (caffe2) zoud@i7:\~$ uname -a
    Linux i7 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pjh5** [comment]
Can you run `nm` on the protobuf installed in your conda environment?

It looks like the current linux Anaconda packages are only compatible with the gcc > 5 ABI, which should work both with your gcc and with the default protobuf in conda. If you already had a different protobuf installed in your conda with a different ABI then that could cause this problem. 

If you see no references to cxx11 in the output of `nm` then you will need to install a different protobuf.

edit: I am unable to reproduce this on clean Ubuntu docker images no matter what gcc I use. The protobuf that libcaffe2 references (which should be the one in the conda environment that it is installed in) needs to have the recent ABI of gcc > 5; the protobuf from the default conda channels has this. Or perhaps you can install protobuf from source with a gcc > 5 and install it into the conda environment, but at that point it's probably easier to just install caffe2 from source

**Comment by 7oud** [comment]
1. When run conda list in my env ‘caffe2’, two protobuf packages "libprotobuf" and "protobuf" are listed, both of them are used in caffe2?  Could you give one of the correct version number of protobuf ? 
2. I chose a mirror conda channel for faster downloading speed, so when run `conda install -c caffe2 caffe2-cuda8.0-cudnn7`, the version of 'libprotobuf' and 'protobuf' are both 3.4.0 in caffe2 env, is it the reason of problem?
3. In order to upgrade protobuf, I downloaded 'protobuf-3.5.1-cp27-cp27mu-manylinux1_x86_64.whl' and pip install it, but it still did not work. There are 3 packages 'libprotobuf 3.4.0' 'protobuf 3.4.0' and 'protobuf 3.5.1' at this time.
4. Then I download 'linux-64/protobuf-3.5.1-py27_3.tar.bz2' from conda-forge and conda install it locally, now 'protobuf 3.4.0' changes into 'protobuf 3.5.1', and still not work. I am not sure which one is used by caffe2, so uninstall protobuf, 'protobuf 3.5.1' is removed, the left two packages are

    (caffe2) zoud@i7:~$ conda list protobuf
    \# packages in environment at /home/zoud/Prog/anaconda2/envs/caffe2:
    \#
    libprotobuf               3.4.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    protobuf                  3.5.1                     <pip>

and runing error changes into "ImportError: No module named google.protobuf.message".

All above is the my experiment, Maybe I can try conda install protobuf using default channel, even it is too slow to install failed usually, or compile protobuf from source code

**Comment by pjh5** [comment]
@7oud this is not about protobuf versions. You can build protobuf 3.4.0 with gcc 4.8.5 or with gcc 5.0.4, and both will result in libprotobuf 3.4.0, but only the one built with gcc 5.0.4 will be compatibile with the other conda packages (including Caffe2) in the default Anaconda channels. The ABI I've been referring to refers to the version of gcc used to build protobuf, not to the version of protobuf itself. Unfortunately, the gcc version is not included in the build-string or in any other metadata about packages in conda at the moment. I do not know the ABI of Tsinghua's mirror, but I know that conda-forge is built with gcc 4.8 (so conda-forge packages are incompatible with ours) and the protobuf from one of these channels:
https://repo.continuum.io/pkgs/main/linux-64
https://repo.continuum.io/pkgs/main/noarch
https://repo.continuum.io/pkgs/free/linux-64
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/linux-64
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/linux-64
https://repo.continuum.io/pkgs/pro/noarch
should be built with gcc 7 and be compatible with ours.

If you run `nm` on a protobuf library then you should be able to find "cxx11" somewhere in the output. `nm` gives a lot of output, so it might be useful to direct the output into a text file.

For more background: `nm` gives all the symbols that are exported by a library, including function definitions and their parameter types. For protobuf libraries built with gcc 4.8.5 or other gcc < 5, some of these exported functions will have `std::string` as parameter types. But in protobuf libraries built with gcc > 5, these functions will instead have `std::__cxx11::string` as parameters. The Caffe2 package in conda links against a protobuf built with gcc 7, and so it expects to find protobuf functions with `std::__cxx11::string` parameters at runtime. If your protobuf library only has functions with `std::string` parameters then Caffe2 will not find the functions it is looking for and will crash at runtime. This is why the error messages usually have "undefined reference" in them, since Caffe2's references to functions with `std::__cxx11::string` parameters were not found anywhere, and so considered undefined by the linker.

**Comment by 7oud** [comment]
Thanks for detailed explanation!

1. When running `nm`, some of the exported symbols

    (caffe2) zoud@i7:~/Prog/anaconda2/envs/caffe2/lib$ nm libprotobuf.so
_ZZN6google8protobuf8compiler12_GLOBAL__N_112MapEntryNameERKNSt7`__cxx1112basic_string`IcSt11char_traitsIcESaIcEEEE7kSuffix
_ZZN6google8protobuf8internal17DefaultLogHandlerENS0_8LogLevelEPKciRKNSt7`__cxx1112basic_string`IcSt11char_traitsIcESaIcEEEE11level_names
    
    (caffe2) zoud@i7:~/Prog/anaconda2/envs/caffe2/lib$ nm libprotobuf.a
_ZNSt7`__cxx1112basic_string`IcSt11char_traitsIcESaIcEE9_M_appendEPKcm
_ZNSt7`__cxx1112basic_string`IcSt11char_traitsIcESaIcEE9_M_assignERKS4_

2. I reinstalled conda caffe using default channel in a new clean environment and installed nccl2 library.  it works now, so the error before is that some packages are compiled using gcc < 5 in Tsinghua channel, Thanks for answering again!

**Comment by 7oud** [comment]
Another question, I build caffe2 from source using default conda channel, then it works ONLY in build dir.
```
(caffe2) zoud@ubu1604:~/Workspace/Github/caffe2/caffe2/build$ python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
1
(caffe2) zoud@ubu1604:~/Workspace/Github/caffe2/caffe2/build$ cd ..
(caffe2) zoud@ubu1604:~/Workspace/Github/caffe2/caffe2$ python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named caffe2.python
```
And caffe2 is not in conda list
```
(caffe2) zoud@ubu1604:~$ conda list caffe2
# packages in environment at /home/zoud/Prog/anaconda2/envs/caffe2:
#
```
How to install compiled caffe2 into env just like other packages expect adding its building path to PYTHONPATH in `.bashrc`, Maybe that will affect other deep learning frameworks. 

Some error info in Detectron installation [https://github.com/facebookresearch/Detectron/issues/220](url)

**Comment by pjh5** [comment]
Conda-build does not create a build dir, so you shouldn't even have that. If that build dir is left over from previous Caffe2 installs that did not use conda, then please delete it. If you have leftover caffe or caffe2 directories under /usr/local, then delete those too.

By "build caffe2 from source using default conda channel" do you mean

1. `conda install caffe2`
2. `conda install -c caffe2 caffe2`
3.
`conda build conda/no_cuda`
`conda install caffe2 --use-local`

In the case of 1, Caffe2 is not in the default channels, so this should have failed. Case 2 and 3 should work, but sometimes people forget the second step of 3. If you use steps 2 or 3 then you shouldn't have to change LD_LIBRARY_PATH or PYTHONPATH.

If you mean that you used https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#custom-anaconda-install , then make sure you are pointing CMAKE_PREFIX_PATH and CMAKE_INSTALL_PATH to your conda environment and that your conda environment is activated when you try and use Caffe2.

**Comment by 7oud** [comment]
@pjh5 
1. I install caffe2 using `conda install -c caffe2 caffe2-cuda8.0-cudnn7` in caffe2 env, it works well when testing `python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'`, but fails to compile and run detectron test
2. I remove the caffe2 env, and reinstall it using `Custom Anaconda Install` with source, and I have set CMAKE_PREFIX_PATH and CMAKE_INSTALL_PATH, it works well ONLY in caffe2/build directory. So I have to add this dir into PYTHONPATH, is it correct ? Even though caffe2 is running OK in both installation methods, but I can not make the Detectron work

**Comment by pjh5** [comment]
If your Anaconda root directory is in home and your env is called myenv then you should need to call cmake with `-DCMAKE_PREFIX_PATH=~/anaconda/envs/myenv` and `-DCMAKE_INSTALL_PREFIX=~/anaconda/envs/myenv` (sorry I called it this variable by the wrong name earlier). Then if you `source activate myenv` you should NOT need to set any other environment variables. Is this what you have tried?

**Comment by 7oud** [comment]
My anaconda2 root directory is '~/Prog/anaconda2' and caffe2 env directory is '/home/zoud/Prog/anaconda2/envs/caffe2'. I set the `-DCMAKE_PREFIX_PATH` and `-DCMAKE_INSTALL_PREFIX` correctly, bcz after `make install`, `libcaffe2.so`, `libcaffe2_gpu.so` are in `~/Prog/anaconda2/envs/caffe2/lib/`. But I can not see caffe2 package when using 'conda list caffe2', and caffe2 works only in caffe2 source code build dir `caffe2/build/`

**Comment by pjh5** [comment]
@7oud can you please open another issue? This is now getting far enough away from the gcc ABI issue to not be relevant on this issue anymore.

**Comment by anatlin** [comment]
@pjh5 could you please give a little more details about running this script https://github.com/caffe2/caffe2/blob/master/scripts/build_anaconda.sh ? What should the $BUILD_ENVIRONMENT be set to? where should the CUDA paths be set?

**Comment by pjh5** [comment]
@anatlin all of the environment variables are actually optional. The script should choose meaningful defaults. The CUDA paths are just used for package naming purposes. You can pass in BUILD_ENVIRONMENT to force behavior, for example you can call `BUILD_ENVIRONMENT=-cuda- scripts/build_anaconda.sh` to force it to build for CUDA.

I'll update my note with a few more details.

**Comment by qinhuan** [comment]
@pjh5 When I build Caffe2 from source, these common errors:
> undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string
So I run 
> CONDA_INSTALL_LOCALLY=1 BUILD_ENVIRONMENT=-cuda- scripts/build_anaconda.sh
And failed. Please help me!

/home/qh/anaconda2/conda-bld/caffe2-cuda-cudnn_1522136840675/work/conda_build.sh: line 107: -DCMAKE_CXX_FLAGS=-D__GLIBCXX_USE_CXX11_ABI=0: command not found
Traceback (most recent call last):
  File "/home/qh/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1240, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/qh/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/qh/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/qh/anaconda2/conda-bld/caffe2-cuda-cudnn_1522136840675/work/conda_build.sh']' returned non-zero exit status 127

**Comment by xyhs2010** [comment]
I try to build caffe2 on debian 9, but failed with:
```
/home/xyhs/coding/util/pytorch/build/lib/libcaffe2.so.1: undefined reference to `google::base::      CheckOpMessageBuilder::NewString()'
/home/xyhs/coding/util/pytorch/build/lib/libcaffe2.so.1: undefined reference to `google::            SetUsageMessage(std::string const&)'
/home/xyhs/coding/util/pytorch/build/lib/libcaffe2.so.1: undefined reference to `leveldb::DB::       Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
/home/xyhs/coding/util/pytorch/build/lib/libcaffe2.so.1: undefined reference to `leveldb::Status::   ToString() const
```

So I try to find out where libleveldb.so located. It turn out to be under "/usr/lib/x86_64-linux-gnu/". So I append this path to $LD_LIBRARY_PATH, and build caffe2 successfully. Maybe this will help somebody.

**Comment by forestriveral** [comment]
@pjh5 It did really hlep me a lot ! I created a new clean conda environment with all packages installed using the default channel and Caffe2 was built successfully, without a single error. The issue that the packages in some Anaconda channels were compiled with a incompatible gcc version,  needs to be noticed for users before building caffe2. Otherwise it do will confuse somebody. Maybe it can appended in the official installation instruction. Anyway thanks for detailed explanation ! 
Besides, for the issue about "conda install -c caffe2 caffe2-cuda9.0-cudnn7" failure, I will post a separate issue description a few days later.
