### ISSUE TITLE
New Caffe2 build w/ GPU, MNIST tutorial works on CPU but fails on GPU at WeightedSum operator

### ISSUE THREAD

**Issue by jzimmerlin** [facebookarchive/caffe2#2077]
Successfully built Caffe2 from master on Ubuntu 16.04 with nvidia 390.30 drivers, latest CUDA 9.1 + cuBLAS patch 1, cuDNN 7.0.5 and NCCL2 2.1.4. This is on a p3.2xl EC2 instance.

Basic caffe2 validations succeed, no GPU warnings and relu op test succeeds. Also found this simple GPU validation in a Detectron post and got the correct result:

```
> python -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
1
```

I ran the MNIST jupyter tutorial as-is on CPU and everything works perfectly.

To validate GPU function, I ran the char_rnn example with "--gpu", and I can see with "nvidia-smi pmon" that it is indeed running on the GPU. Everything appears to be linked properly.

So then I tried to get the MNIST tutorial to run on the GPU. I am new to Caffe2, but found some posts indicating that you can make it use a GPU by adding the following after train_model is defined:

```
train_model.net.RunAllOnGPU(gpu_id=0, use_cudnn=True)
train_model.param_init_net.RunAllOnGPU(gpu_id=0, use_cudnn=True)
```

I added this in the jupyter notebook and restarted the kernel, and then ran everything again. The above cell executed without issue, but then I got this output from the cell containing "workspace.RunNetOnce(train_model.param_init_net)":

```
Traceback for operator 28 in network mnist_train
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:272
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:65
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:1080
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:1112
<ipython-input-8-17dabd1c635d>:15
<ipython-input-10-b120a938f524>:13
/home/ubuntu/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2882
/home/ubuntu/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2822
/home/ubuntu/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/zmqshell.py:537
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/ipkernel.py:208
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py:399
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py:233
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py:283
/home/ubuntu/.local/lib/python2.7/site-packages/tornado/stack_context.py:277
/home/ubuntu/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py:432
/home/ubuntu/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py:480
/home/ubuntu/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py:450
/home/ubuntu/.local/lib/python2.7/site-packages/tornado/stack_context.py:277
/home/ubuntu/.local/lib/python2.7/site-packages/tornado/ioloop.py:888
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py:486
/home/ubuntu/.local/lib/python2.7/site-packages/traitlets/config/application.py:658
/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel_launcher.py:16
/usr/lib/python2.7/runpy.py:72
/usr/lib/python2.7/runpy.py:174
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-14-575100cdd26e> in <module>()
     17 # Now, we will manually run the network for 200 iterations.
     18 for i in range(total_iters):
---> 19     workspace.RunNet(train_model.net)
     20     accuracy[i] = workspace.blobs['accuracy']
     21     loss[i] = workspace.blobs['loss']

/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.pyc in RunNet(name, num_iter, allow_fail)
    222         C.Workspace.current._last_failed_op_net_position,
    223         GetNetName(name),
--> 224         StringifyNetName(name), num_iter, allow_fail,
    225     )
    226 

/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.pyc in CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs)
    187 def CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs):
    188     try:
--> 189         return func(*args, **kwargs)
    190     except Exception:
    191         op_id = op_id_fetcher()

SystemError: error return without exception set
```

I uncommented the logging env vars in start_ipython_notebook.sh, but then stumbled on the de-jupytered tutorial code at caffe2/build/caffe2/python/tutorials/py_gen/MNIST.py, ran it on the command-line and got the same result but a bit more detail in the log output:

```
...
I0228 06:29:19.514825  3918 net_simple.cc:64] Running operator (MaxPoolGradient).
I0228 06:29:19.514842  3918 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0228 06:29:19.514850  3918 pool_op_cudnn.cu:425] Changing the cudnn descriptor configurations.
I0228 06:29:19.515094  3918 net_simple.cc:64] Running operator (ConvGradient).
I0228 06:29:19.515120  3918 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0228 06:29:19.515137  3918 conv_op_cudnn.cc:715] Changing the cudnn descriptor configurations.
I0228 06:29:19.515177  3918 conv_op_cudnn.cc:998] CuDNN bwd algorithm: 0, 0
I0228 06:29:19.515189  3918 conv_op_cudnn.cc:1000] CuDNN workspace size: 0
I0228 06:29:19.515198  3918 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0228 06:29:19.515334  3918 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0228 06:29:19.515485  3918 net_simple.cc:64] Running operator (AtomicIter).
I0228 06:29:19.515506  3918 net_simple.cc:64] Running operator (LearningRate).
I0228 06:29:19.515522  3918 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CPUContext>
I0228 06:29:19.515573  3918 net_simple.cc:64] Running operator (WeightedSum).
I0228 06:29:19.515803  3918 operator.h:212] Operator with id 28 failed
Traceback for operator 28 in network mnist_train
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:272
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:65
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:1080
/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py:1112
MNIST.py:270
MNIST.py:326
Traceback (most recent call last):
  File "MNIST.py", line 414, in <module>
    workspace.RunNet(train_model.net)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 224, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 189, in CallWithExceptionIntercept
    return func(*args, **kwargs)
SystemError: error return without exception set
```

I'm unsure how to proceed from here. What I do know is that the MNIST tutorial works fine on CPU but fails as above when I attempt to enable GPU. Most of the operators in the graph seem to execute without issue, but this WeightedSum op fails without providing any details. Is there another source of diagnostic information for cases like this, where we are crossing a boundary between python and native code?

**Comment by jzimmerlin** [comment]
So I re-built from latest master (minus the latest broken commits) and tried again, and unsure whether it was some commit since the first attempt or the alignment of the moon, but this time, an exception was returned from the operator:

```
/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py in CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs)
    187 def CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs):
    188     try:
--> 189         return func(*args, **kwargs)
    190     except Exception:
    191         op_id = op_id_fetcher()

RuntimeError: [enforce fail at blob.h:97] IsType<T>(). wrong type for the Blob instance. Blob contains caffe2::Tensor<caffe2::CUDAContext> while caller expects caffe2::Tensor<caffe2::CPUContext> .
Offending Blob name: pred_b.
Error from operator: 
input: "pred_b" input: "ONE_0_0" input: "pred_b_grad" input: "SgdOptimizer_1_lr_cpu" output: "pred_b" name: "" type: "WeightedSum" device_option { } debug_info: "  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n    app.start()\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 486, in start\n    self.io_loop.start()\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tornado/ioloop.py\", line 888, in start\n    handler_func(fd_obj, events)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py\", line 450, in _handle_events\n    self._handle_recv()\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py\", line 480, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py\", line 432, in _run_callback\n    callback(*args, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 233, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/ipkernel.py\", line 208, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/zmqshell.py\", line 537, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py\", line 2705, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py\", line 2809, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py\", line 2869, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-41-c9e3ea45e0e7>\", line 12, in <module>\n    AddTrainingOperators(train_model, softmax, label)\n  File \"<ipython-input-9-46ebb94ac305>\", line 15, in AddTrainingOperators\n    gamma=0.999,\n  File \"/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py\", line 1112, in build_sgd\n    allow_lr_injection=allow_lr_injection,\n  File \"/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py\", line 1080, in _build\n    optimizer(model.net, model.param_init_net, param_info)\n  File \"/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py\", line 65, in __call__\n    self._run(net, param_init_net, param)\n  File \"/usr/local/lib/python2.7/dist-packages/caffe2/python/optimizer.py\", line 272, in _run\n    param\n  File \"/usr/local/lib/python2.7/dist-packages/caffe2/python/core.py\", line 2047, in <lambda>\n    op_type, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/caffe2/python/core.py\", line 2024, in _CreateAndAddToSelf\n    op = CreateOperator(op_type, inputs, outputs, **kwargs)\n"
```

I did change a couple things with this build, but don't see how they would be related to getting an exception where it previously failed without providing any information - I did not install the latest NCCL2 library prior to building Caffe2, and I also enabled the AVX extensions in CMakeLists.

Now looking at the log output tracking the execution graph, I see that some operators appear to be running on the GPU while at least the one that is failing is not:

```
...
I0302 04:52:56.625537 12194 net_simple.cc:64] Running operator (ConvGradient).
I0302 04:52:56.625556 12194 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0302 04:52:56.625569 12194 conv_op_cudnn.cc:715] Changing the cudnn descriptor configurations.
I0302 04:52:56.625598 12194 conv_op_cudnn.cc:998] CuDNN bwd algorithm: 0, 0
I0302 04:52:56.625609 12194 conv_op_cudnn.cc:1000] CuDNN workspace size: 0
I0302 04:52:56.625617 12194 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0302 04:52:56.625713 12194 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CUDAContext>
I0302 04:52:56.625883 12194 net_simple.cc:64] Running operator (AtomicIter).
I0302 04:52:56.625898 12194 net_simple.cc:64] Running operator (LearningRate).
I0302 04:52:56.625908 12194 blob.h:123] Create new mutable object caffe2::Tensor<caffe2::CPUContext>
I0302 04:52:56.625946 12194 net_simple.cc:64] Running operator (WeightedSum).
I0302 04:52:56.626042 12194 operator.h:212] Operator with id 28 failed
```

Earlier in the log, I see where it is constructing the graph, and some of the operators report "Operator with engine CUDNN is not available". Digging through the source, I see that a factory abstraction is involved in creating operator instances, so I'm guessing there is more to enabling the GPU than the couple of lines that I added.

I also notice that all of the operators leading up to the SGD optimizer step report a "device type" of 1, and then they suddenly switch to 0, so I'm guessing type 1 is GPU and 0 is CPU?

```
I0302 04:52:56.616979 12194 net_simple.cc:41] Creating operator : MaxPoolGradient
I0302 04:52:56.616994 12194 operator.cc:159] Trying to create operator MaxPoolGradient with engine CUDNN
I0302 04:52:56.617003 12194 operator.cc:99] Creating operator with device type 1
I0302 04:52:56.617020 12194 workspace.cc:128] Creating blob conv1_grad
...
I0302 04:52:56.617190 12194 net_simple.cc:41] Creating operator : ConvGradient
I0302 04:52:56.617208 12194 operator.cc:159] Trying to create operator ConvGradient with engine CUDNN
I0302 04:52:56.617218 12194 operator.cc:99] Creating operator with device type 1
I0302 04:52:56.617230 12194 workspace.cc:128] Creating blob conv1_w_grad
I0302 04:52:56.617240 12194 workspace.cc:128] Creating blob conv1_b_grad
I0302 04:52:56.617250 12194 workspace.cc:128] Creating blob data_grad
...
I0302 04:52:56.617486 12194 net_simple.cc:41] Creating operator : AtomicIter
I0302 04:52:56.617498 12194 operator.cc:176] Using default implementation.
I0302 04:52:56.617506 12194 operator.cc:99] Creating operator with device type 0
I0302 04:52:56.617522 12194 workspace.cc:122] Blob optimizer_iteration already exists. Skipping.
I0302 04:52:56.617534 12194 net_simple.cc:41] Creating operator : LearningRate
I0302 04:52:56.617547 12194 operator.cc:176] Using default implementation.
I0302 04:52:56.617555 12194 operator.cc:99] Creating operator with device type 0
I0302 04:52:56.617565 12194 workspace.cc:128] Creating blob SgdOptimizer_2_lr_cpu
I0302 04:52:56.617588 12194 net_simple.cc:41] Creating operator : WeightedSum
I0302 04:52:56.617599 12194 operator.cc:176] Using default implementation.
I0302 04:52:56.617607 12194 operator.cc:99] Creating operator with device type 0
```

**Comment by jzimmerlin** [comment]
Oh, I was way off. This was the solution:

```
device = core.DeviceOption(caffe2_pb2.CUDA, 0)
with core.DeviceScope(device):
    <everything>
```

Closing issue.
