### ISSUE TITLE
ImportError when importing caffe2.python.onnx.backend

### ISSUE THREAD

**Issue by jo7ueb** [facebookarchive/caffe2#2173]
Hi, I'm evaluating ONNX feature for 6b5886b.

I got following ImportError when importing `caffe2.python.onnx.backend`
```
root@91b3c88b45be:/yendo/codes/tech-research/nnframework/onnx# python3 -c 'import caffe2.python.onnx'
root@91b3c88b45be:/yendo/codes/tech-research/nnframework/onnx# python3 -c 'import caffe2.python.onnx.backend'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/caffe2/python/onnx/backend.py", line 42, in <module>
    import onnx.optimizer
ImportError: No module named 'onnx.optimizer'
```

I have installed onnx already.
```
root@91b3c88b45be:/caffe2# pip3 list | grep onnx
onnx (0.2.1)
onnx-chainer (1.0.0a1)
onnx-mxnet (0.4.2)
onnx-tf (1.0)
```

What's the solution for this issue?

Thanks.

**Comment by houseroad** [comment]
your onnx package is too old. (experimental) optimizer is just introduced, please uninstall onnx, and try to install it from the github.

**Comment by jo7ueb** [comment]
@houseroad Thank you for your comment.
My problem is fixed with newer onnx installation.
