### ISSUE TITLE
libnccl.so.2: cannot open shared object file and undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

### ISSUE THREAD

**Issue by fengyicoder** [facebookarchive/caffe2#2190]
I install the caffe2 with anaconda by excuting "conda install -c caffe2 caffe2-cuda9.0-cudnn7",then when I want to confirm wether the installation is successful, and excuting "from caffe2.python import workspace ", the error appear as below:
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: /home/flyfree/anaconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
what should I do? Please help me, thanks!

**Comment by pjh5** [comment]
There are two problems here.

First, you must have NCCL 2 installed for this package to work. See Nvidia's instructions here http://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html or our install script here https://github.com/caffe2/caffe2/blob/master/docker/jenkins/common/install_nccl.sh . Your Caffe2 installation will not work without NCCL 2.

Second, there is a protobuf gcc ABI mismatch on your system. This package was built with a protobuf library that was compiled against gcc 7.2, and so it is incompatible with protobuf libraries that were compiled against gcc < 5 . See this issue #1980 for more background. You may have to build Caffe2 from source on your machine to get around this.

**Comment by fengyicoder** [comment]
@pjh5 I try to install the NCCL 2, however, the error 'libnccl2 rely cuda-cudart-9-0 but can't install it'appear. Then I try to install caffe2 from source,the error is as follow:
[ 77%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/learning_rate_op_gpu.cc.o
CMakeFiles/Makefile2:3056: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/flyfree/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1776, in build_tree
    notest=notest,
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1122, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 676, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/flyfree/anaconda2/lib/python2.7/site-packages/conda_build/utils.py", line 672, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/flyfree/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/flyfree/anaconda2/conda-bld/caffe2-cuda_1520573551098/work/conda_build.sh']' returned non-zero exit status 2
