### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by gowtamhareesh** [facebookarchive/caffe2#2441]
I have built caffe2 source successfully on Ubuntu 16.04. 
when I use the command **python -c 'import caffe2.python.onnx.frontend'**
its gives following error:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe2/python/onnx/frontend.py", line 37, in <module>
    from onnx import (defs, checker, helper, numpy_helper, mapping,
  File "/usr/local/lib/python2.7/dist-packages/onnx/__init__.py", line 6, in <module>
    from .onnx_pb import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_pb2 import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/onnx/onnx_pb2.py", line 23, in <module>
    8\x01 \x01(\x0e\x32\x1a.onnx.TensorProto.DataType\x12%\n\x05shape\x18\x02 \x01(\x0b\x32\x16.onnx.TensorShapeProtoB\x07\n\x05value\"5\n\x12OperatorSetIdProto\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03*c\n\x07Version\x12\x12\n\x0e_START_VERSION\x10\x00\x12\x19\n\x15IR_VERSION_2017_10_10\x10\x01\x12\x19\n\x15IR_VERSION_2017_10_30\x10\x02\x12\x0e\n\nIR_VERSION\x10\x03')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

### System information

* Operating system: Ubuntu 16.04.3 LTS (GNU/Linux 4.10.0-28-generic x86_64)
* Compiler version:  GNU 5.4.0
* CMake version: 3.5.1
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):
   **No CUDA
   Python 2.7.12
   Protobuf 3.5.1 ( installed from source)**
    

### CMake summary output

```
******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1416-gae7f3d5-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : 
--   Protobuf include path : 
--   Protobuf libraries    : 
--   BLAS                  : Eigen
--   CXX flags             :  -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : OFF
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.9.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done

```

**Comment by gowtamhareesh** [comment]
I found the issue.
I was using onnx installed via pip which was compiled using protobuf version different than the one used to build caffe2(libprotoc 3.5.1).
I cloned latest onnx source (1.1.0) and complied it using same protobuf caffe2 was using.
This solved the issue.

**Comment by Mohammed-Shoaib** [comment]
@gowtamhareesh You are like the best.
You actually firgured it out and bothered to come and post here what went wrong for people who might face the same issue.
Thank you so much for that.
