### ISSUE TITLE
Some problems when checking the custom operator test :  OSError: libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6caffe213EnforceNotMet13AppendMessageERKSs

### ISSUE THREAD

**Issue by kwanyeelin** [facebookarchive/caffe2#2535]
I install the caffe2 with anaconda by executing "conda install -c caffe2 caffe2-cuda9.0-cudnn7", then when I want to check whether the custom operator test pass (run the test_zero_env_op.py), the error appear as below:
-----------------------------------------------------------------------------------------------------------------------
E0703 20:29:07.268339 12399 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0703 20:29:07.268440 12399 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0703 20:29:07.268460 12399 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "test_zero_even_op.py", line 117, in <module>
    c2_utils.import_custom_ops()
  File "/mnt/workspace_2/densepose_repo/detectron/utils/c2.py", line 40, in import_custom_ops
    dyndep.InitOpsLibrary(custom_ops_lib)
  File "/mnt/anaconda2/envs/caffe2_env/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/mnt/anaconda2/envs/caffe2_env/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/mnt/anaconda2/envs/caffe2_env/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /mnt/workspace_2/densepose_repo/build/libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6caffe213EnforceNotMet13AppendMessageERKSs****
-----------------------------------------------------------------------------------------------------------------------I    
I don't know how to solve the problem, please help me, thank you!

**Comment by huhai463127310** [comment]
I meet same issue in miniconda env, and I don't know how to resolve it.

OS version: CentOS Linux release 7.5.1804 (Core) 
python version: Python 2.7.15 :: Anaconda, Inc.

**exception stack**:

```
E0706 19:35:15.719159 52390 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0706 19:35:15.719207 52390 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0706 19:35:15.719213 52390 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "detectron/tests/test_zero_even_op.py", line 117, in <module>
    c2_utils.import_custom_ops()
  File "/home/ai/densepose/detectron/utils/c2.py", line 40, in import_custom_ops
    dyndep.InitOpsLibrary(custom_ops_lib)
  File "/home/ai/miniconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/ai/miniconda2/envs/caffe2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/ai/miniconda2/envs/caffe2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ai/densepose/build/libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6caffe213EnforceNotMet13AppendMessageERKSs
```

I check with undefined symbol with command "ldd -r build/libcaffe2_detectron_custom_ops_gpu.so " ,  found more than one undefined symbol issue.

```
build/libcaffe2_detectron_custom_ops_gpu.so: /home/root/local/cudnn-7.1.2/lib64/libcudnn.so.7: no version information available (required by /home/ai/miniconda2/envs/caffe2/lib/libcaffe2_gpu.so)
        linux-vdso.so.1 =>  (0x00007ffd517bd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6eeb7db000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f6eeb5d6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f6eeb3ce000)
        libcaffe2_gpu.so => /home/ai/miniconda2/envs/caffe2/lib/libcaffe2_gpu.so (0x00007f6ee7340000)
        libcaffe2.so => /home/ai/miniconda2/envs/caffe2/lib/libcaffe2.so (0x00007f6ee632f000)
        libglog.so.0 => /home/ai/miniconda2/envs/caffe2/lib/libglog.so.0 (0x00007f6ee60fe000)
        libcurand.so.9.0 => /usr/local/cuda/lib64/libcurand.so.9.0 (0x00007f6ee219a000)
        libstdc++.so.6 => /home/ai/miniconda2/envs/caffe2/lib/libstdc++.so.6 (0x00007f6ee1e5f000)
        libgcc_s.so.1 => /home/ai/miniconda2/envs/caffe2/lib/libgcc_s.so.1 (0x00007f6ee1c4d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f6ee1880000)
        /lib64/ld-linux-x86-64.so.2 (0x00005637ff23f000)
        libcuda.so.1 => /usr/lib64/nvidia/libcuda.so.1 (0x00007f6ee0bf2000)
        libcudnn.so.7 => /home/root/local/cudnn-7.1.2/lib64/libcudnn.so.7 (0x00007f6ed4793000)
        libnvrtc.so.9.0 => /home/ai/miniconda2/envs/caffe2/lib/./libnvrtc.so.9.0 (0x00007f6ed2f47000)
        libnccl.so.2 => /usr/local/nccl/lib/libnccl.so.2 (0x00007f6ec69dd000)
        libgflags.so.2.2 => /home/ai/miniconda2/envs/caffe2/lib/./libgflags.so.2.2 (0x00007f6ec67b8000)
        libcublas.so.9.0 => /home/ai/miniconda2/envs/caffe2/lib/./libcublas.so.9.0 (0x00007f6ec337f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f6ec307c000)
        libopencv_imgcodecs.so.3.3 => /home/ai/miniconda2/envs/caffe2/lib/./libopencv_imgcodecs.so.3.3 (0x00007f6ec2977000)
        libopencv_imgproc.so.3.3 => /home/ai/miniconda2/envs/caffe2/lib/./libopencv_imgproc.so.3.3 (0x00007f6ebfcd5000)
        libopencv_core.so.3.3 => /home/ai/miniconda2/envs/caffe2/lib/./libopencv_core.so.3.3 (0x00007f6ebee54000)
        libnvidia-fatbinaryloader.so.387.26 => /usr/lib64/nvidia/libnvidia-fatbinaryloader.so.387.26 (0x00007f6ebec01000)
        libcudart.so.8.0 => /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0 (0x00007f6ebe99b000)
        libjpeg.so.9 => /home/ai/miniconda2/envs/caffe2/lib/././libjpeg.so.9 (0x00007f6ebe75e000)
        libpng16.so.16 => /home/ai/miniconda2/envs/caffe2/lib/././libpng16.so.16 (0x00007f6ebe527000)
        libtiff.so.5 => /home/ai/miniconda2/envs/caffe2/lib/././libtiff.so.5 (0x00007f6ebe2ad000)
        libjasper.so.4 => /home/ai/miniconda2/envs/caffe2/lib/././libjasper.so.4 (0x00007f6ebe04e000)
        libz.so.1 => /home/ai/miniconda2/envs/caffe2/lib/././libz.so.1 (0x00007f6ebde37000)
        libgomp.so.1 => /home/ai/miniconda2/envs/caffe2/lib/././libgomp.so.1 (0x00007f6ebdc13000)
        liblzma.so.5 => /home/ai/miniconda2/envs/caffe2/lib/./././liblzma.so.5 (0x00007f6ebd9ed000)
undefined symbol: _ZN6caffe213EnforceNotMet13AppendMessageERKSs (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe227GetEmptyStringAlreadyInitedEv     (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe210gTypeNamesEv      (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe213EnforceNotMetC1EPKciS2_RKSsPKv    (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringEv    (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe216OpSchemaRegistry3mapEv    (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe219CPUOperatorRegistryEv     (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe216ProtoDebugStringERKN6google8protobuf7MessageE     (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe216GradientRegistryEv        (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZNK6caffe214ArgumentHelper17GetSingleArgumentIfEET_RKSsRKS2_ (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe220CUDAOperatorRegistryEv    (build/libcaffe2_detectron_custom_ops_gpu.so)
undefined symbol: _ZN6caffe28DemangleEPKc       (build/libcaffe2_detectron_custom_ops_gpu.so)

```

**Comment by ypflll** [comment]
@huhai463127310  Same problem. Wondering have you fixed it?

**Comment by ethanhe42** [comment]
Same problem. Wondering have you fixed it?

**Comment by orionr** [comment]
Thank you for reporting this. Just to confirm, are you checking out and building from https://github.com/pytorch/pytorch ? Caffe2 and PyTorch have merged together in that repository. If this is still an issue, please open an issue at https://github.com/pytorch/pytorch/issues/ and we'll take a look. Feel free to cc me on the issue as well. Thanks.

**Comment by ypflll** [comment]
@orionr Yes.  Finally, I turn to docker.

**Comment by ethanhe42** [comment]
@orionr Yes.

**Comment by orionr** [comment]
I'll investigate, but in the meantime you can temporarily disable default hidden visibility by making the following change:

```
diff --git a/caffe2/CMakeLists.txt b/caffe2/CMakeLists.txt
index 4e9b3eef8..a864166c4 100644
--- a/caffe2/CMakeLists.txt
+++ b/caffe2/CMakeLists.txt
@@ -196,9 +196,6 @@ target_link_libraries(caffe2_protos PUBLIC protobuf::libprotobuf)
 # Compile exposed libraries.
 list(APPEND Caffe2_CPU_SRCs $<TARGET_OBJECTS:c10>)
 add_library(caffe2 ${Caffe2_CPU_SRCS})
-if (NOT WIN32)
-  target_compile_options(caffe2 PRIVATE "-fvisibility=hidden")
-endif()
 caffe2_interface_library(caffe2_protos caffe2_protos_whole)
 target_link_libraries(caffe2 PRIVATE caffe2_protos_whole)
 if (${CAFFE2_LINK_LOCAL_PROTOBUF})
```
Let me know if this works as a temporary fix.

**Comment by orionr** [comment]
@ypflll and @yihui-he - doesn't look like there's anything obvious here... The symbols I checked above look to be prefixed correctly. Let me know if exporting all symbols works for you with the patch.
