### ISSUE TITLE
Understanding Net Creation, Train, Test

### ISSUE THREAD

**Issue by tarunjainsagar** [facebookarchive/caffe2#337]
1. I created a net with python code.
```
#
#       Model Definition
#

# Create Model using a MODEL HELPER
model   = cnn.CNNModelHelper(name="First Simple Model")

# Adding Fully Connected Layer to model object
fc_1    = model.FC("data", "fc_1", dim_in=100, dim_out=10)      # Input Dimension = 100; Output Dimension = 10
                                                                # Input = Data Blob; Output = FC_1 Blob

# Adding Sigmoid Layer to model
pred    = model.Sigmoid( fc_1, "pred")                          # Input = FC_1 Blob; Output = pred Blob

# Adding Softmax with Loss Layer
[softmax, loss] = model.SoftmaxWithLoss( [pred, "label"], ["softmax", "loss"])

```
2. Initialized Parameter of Net FC Layer

```
# Initialize Parameters
workspace.RunNetOnce( model.param_init_net)
```

Please tell next step to first train NET and test it.

I m confused with this code `workspace.CreateNet( model.net)` as it asks for Blob.
See Full Program and error below:
```
from caffe2.python import workspace, cnn
import numpy as np

#
#       Model Definition
#

# Create Model using a MODEL HELPER
model   = cnn.CNNModelHelper(name="First Simple Model")

# Adding Fully Connected Layer to model object
fc_1    = model.FC("data", "fc_1", dim_in=100, dim_out=10)      # Input Dimension = 100; Output Dimension = 10
                                                                # Input = Data Blob; Output = FC_1 Blob

# Adding Sigmoid Layer to model
pred    = model.Sigmoid( fc_1, "pred")                          # Input = FC_1 Blob; Output = pred Blob

# Adding Softmax with Loss Layer
[softmax, loss] = model.SoftmaxWithLoss( [pred, "label"], ["softmax", "loss"])

#
#       Creating Actual Net - Training Net on Data -  One Time Step
#

# Initialize Parameters
workspace.RunNetOnce( model.param_init_net)

# Create Net
workspace.CreateNet(model.net)

```

Error:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0420 09:58:44.791779 34030 workspace.cc:244] Blob data not in the workspace.
Traceback (most recent call last):
  File "04_Forward_Only_Executing_Model.py", line 44, in <module>
    workspace.CreateNet(model.net)
  File "/home/tarun/downloads/new_caffe2/build/caffe2/python/workspace.py", line 145, in CreateNet
    return C.create_net(StringifyProto(net), overwrite)
RuntimeError: [enforce fail at operator.cc:26] blob != nullptr. op FC: Encountered a non-existing input blob: data
```

If I provide blob information like this before running CreateNET() , the error does not come. 
```
## Create the input data
data = np.random.rand(16, 100).astype(np.float32)

# Create labels for the data as integers [0, 9].
label = (np.random.rand(16) * 10).astype(np.int32)

workspace.FeedBlob("data", data)
workspace.FeedBlob("label", label)
```

What is happening please explain.

**Comment by bwasti** [comment]
Operators validate the existence of their inputs when created.  CreateNet instantiates every operator to be real objects so the existence all of the data inputs are checked (the blobs themselves must exist).  If you are looking to later change the input data that is possible, see Tensor::ShareData and as an example [predictor's shareInputTensor](https://github.com/caffe2/caffe2/blob/master/caffe2/core/predictor.cc#L14-L24).

**Comment by bwasti** [comment]
For the python interface, what you did was correct: feeding the data into a "data" blob before calling CreateNet.

**Comment by tarunjainsagar** [comment]
Dear @bwasti, Thanks for such fast response. 
So now, my question is:

**Ques. 01**
I want to create a training network with FC, Sigmoid, SoftmaxWithLoss Layers. 
Do I feed all the training data blob into workspace before running CreateNet for Training Model Definition ?

**Ques. 02**
If above statement is true, then is the following way correct to perform 100 training iteration on fed data:
```
# Run 100 x 10 iterations
for j in range(0, 100):
    data = np.random.rand(16, 100).astype(np.float32)
    label = (np.random.rand(16) * 10).astype(np.int32)

    workspace.FeedBlob("data", data)
    workspace.FeedBlob("label", label)

    workspace.RunNet(m.name, 10)   # run for 10 times
```
Where do we add createNet for this ?


**Ques. 03**
If above is true, I want to know, how do I save the trained model to run testing on my testing data ? Do we need to create separate NET for testing ?
Tutorials here do not explain it clearly : **http://caffe2.ai/docs/intro-tutorial**


If possible, can you give a complete example below with above requirements, Questions are mentioned in comments:
```
from caffe2.python import workspace, cnn
import numpy as np

#
#	Model Definition
#

# Create Model using a MODEL HELPER
model 	= cnn.CNNModelHelper(name="First Simple Model")

# Adding Fully Connected Layer to model object
fc_1  	= model.FC("data", "fc_1", dim_in=100, dim_out=10)	# Input Dimension = 100; Output Dimension = 10
								# Input = Data Blob; Output = FC_1 Blob

# Adding Sigmoid Layer to model
pred	= model.Sigmoid( fc_1, "pred")				# Input = FC_1 Blob; Output = pred Blob

# Adding Softmax with Loss Layer
[softmax, loss]	= model.SoftmaxWithLoss( [pred, "label"], ["softmax", "loss"])

# Initialize Parameters - One Time Step
workspace.RunNetOnce( model.param_init_net)

#
#       **Adding Entire Training Data to Workspace - For 100 iterations**
#
for j in range(0,100):
	# Create the input data for 
	data = np.random.rand(16, 100).astype(np.float32)

	# Create labels for the data as integers [0, 9].
	label = (np.random.rand(16) * 10).astype(np.int32)

	workspace.FeedBlob("data", data)
	workspace.FeedBlob("label", label)

#
#       Create Net
#
workspace.CreateNet(model.net)

#
#       Running Training Net - 100 iterations
#
for j in range(0,100):
	workspace.RunNet(model.name, 10)			# 10 times
        **#QUESTION                                               # Which Blob Does it Pick up everytime ?????????**

	print("\n Softmax:")
	print(workspace.FetchBlob("softmax"))

	print("\nLoss :")
	print(workspace.FetchBlob("loss"))


#
#       Testing Phase ?????? - What to do ????
#

```

**Comment by lironmo** [comment]
I also would like to know this. The paradigm of training seems to be blackbox, which is hard to set different strategies.
