### ISSUE TITLE
Translation of bvlc_alexnet fails

### ISSUE THREAD

**Issue by sherifshehata** [facebookarchive/caffe2#341]
I am trying to to convert bvlc's alexnet to caffe2 format, but i get erros. I am using the command:
`python -m caffe2.python.caffe_translator deploy.prototxt bvlc_alexnet.caffemodel`

I get this error message
"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/caffe2/python/caffe_translator.py", line 612, in <module>
    init_net = ConvertTensorProtosToInitNet(pretrained_params, external_input)
  File "/usr/local/caffe2/python/caffe_translator.py", line 150, in ConvertTensorProtosToInitNet
    utils.MakeArgument("values", tensor.float_data)])
  File "/usr/local/caffe2/python/utils.py", line 101, in MakeArgument
    (key, str(value), str(type(value)))
ValueError: Unknown argument type: key=values value=[
"

**Comment by harouwu** [comment]
Hi @sherifshehata ,

Seems like you are getting this error because one of arguments in your model file is missing. Would you mind checking that if you are using the right model and the right deploy.prototxt?

I just pull the latest Caffe2 repo, download model and deploy.prototxt. I ran the translator for bvlc_alexnet model. Everything went fine.  Here are the result. Please ignore the .3 after deploy.prototxt. :)

```
python -m caffe2.python.caffe_translator deploy.prototxt.3 bvlc_alexnet.caffemodel
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
INFO:caffe_translator:Translate layer data
INFO:caffe_translator:Translate layer conv1
INFO:caffe_translator:Translate layer relu1
INFO:caffe_translator:Translate layer norm1
INFO:caffe_translator:Translate layer pool1
INFO:caffe_translator:Translate layer conv2
INFO:caffe_translator:Translate layer relu2
INFO:caffe_translator:Translate layer norm2
INFO:caffe_translator:Translate layer pool2
INFO:caffe_translator:Translate layer conv3
INFO:caffe_translator:Translate layer relu3
INFO:caffe_translator:Translate layer conv4
INFO:caffe_translator:Translate layer relu4
INFO:caffe_translator:Translate layer conv5
INFO:caffe_translator:Translate layer relu5
INFO:caffe_translator:Translate layer pool5
INFO:caffe_translator:Translate layer fc6
INFO:caffe_translator:Translate layer relu6
INFO:caffe_translator:Translate layer drop6
INFO:caffe_translator:Translate layer fc7
INFO:caffe_translator:Translate layer relu7
INFO:caffe_translator:Translate layer drop7
INFO:caffe_translator:Translate layer fc8
INFO:caffe_translator:Translate layer prob
```

**Comment by sherifshehata** [comment]
I used the depoly and caffe models from caffe's model zoo. Unfortunately i won't be able to try this again till one week later, as i don't have access to the machine.

**Comment by harouwu** [comment]
@sherifshehata we will check our model zoo at the same time /cc: @aaronmarkham

**Comment by aaronmarkham** [comment]
I tried both the places this resides - on the bvlc repo and in our models repo and translation worked fine for both. I've made the mistake of fetching a file from github and it bringing a bunch of github site payload with it versus the raw file... maybe that's what you did? For example, wget https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/deploy.prototxt will create a file full of html instead of what you thought it was going to bring down. Feel free to reopen if you're still running into a problem.

**Comment by sherifshehata** [comment]
Yes that's what i did. Sorry for that silly mistake :)

**Comment by afshindn** [comment]
I faced this problem today. My repo is up-to-date

 ```Shell
python -m caffe2.python.caffe_translator deploy.prototxt model.caffemodel

INFO:caffe_translator:Translate layer conv1
INFO:caffe_translator:Translate layer relu1
INFO:caffe_translator:Translate layer norm1
INFO:caffe_translator:Translate layer conv2
INFO:caffe_translator:Translate layer relu2
INFO:caffe_translator:Translate layer norm2
INFO:caffe_translator:Translate layer pool1
INFO:caffe_translator:Translate layer conv3
INFO:caffe_translator:Translate layer relu3
INFO:caffe_translator:Translate layer pool2
INFO:caffe_translator:Translate layer conv4
INFO:caffe_translator:Translate layer relu4
INFO:caffe_translator:Translate layer pool3
INFO:caffe_translator:Translate layer conv5
INFO:caffe_translator:Translate layer relu5
INFO:caffe_translator:Translate layer pool4
INFO:caffe_translator:Translate layer fc
INFO:caffe_translator:Translate layer prob
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/caffe2/python/caffe_translator.py", line 612, in <module>
    init_net = ConvertTensorProtosToInitNet(pretrained_params, external_input)
  File "/usr/local/caffe2/python/caffe_translator.py", line 150, in ConvertTensorProtosToInitNet
    utils.MakeArgument("values", tensor.float_data)])
  File "/usr/local/caffe2/python/utils.py", line 101, in MakeArgument
    (key, str(value), str(type(value)))
ValueError: Unknown argument type: key=values value=[-0.22154687345027924, ...

  ```

**Comment by afshindn** [comment]
Facing the same issue. Just cloned the repo and quickly tried the translator on a simple local model. 

  ```Shell
python -m caffe2.python.caffe_translator deploy.prototxt model.caffemodel

INFO:caffe_translator:Translate layer conv1
INFO:caffe_translator:Translate layer relu1
INFO:caffe_translator:Translate layer norm1
INFO:caffe_translator:Translate layer conv2
INFO:caffe_translator:Translate layer relu2
INFO:caffe_translator:Translate layer norm2
INFO:caffe_translator:Translate layer pool1
INFO:caffe_translator:Translate layer conv3
INFO:caffe_translator:Translate layer relu3
INFO:caffe_translator:Translate layer pool2
INFO:caffe_translator:Translate layer conv4
INFO:caffe_translator:Translate layer relu4
INFO:caffe_translator:Translate layer pool3
INFO:caffe_translator:Translate layer conv5
INFO:caffe_translator:Translate layer relu5
INFO:caffe_translator:Translate layer pool4
INFO:caffe_translator:Translate layer fc
INFO:caffe_translator:Translate layer prob
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/caffe2/python/caffe_translator.py", line 612, in <module>
    init_net = ConvertTensorProtosToInitNet(pretrained_params, external_input)
  File "/usr/local/caffe2/python/caffe_translator.py", line 150, in ConvertTensorProtosToInitNet
    utils.MakeArgument("values", tensor.float_data)])
  File "/usr/local/caffe2/python/utils.py", line 101, in MakeArgument
    (key, str(value), str(type(value)))
ValueError: Unknown argument type: key=values value=[-0.22154687345027924,

```

**Comment by sherifshehata** [comment]
I repeated the experiment, i downloaded the model using the ipython tutotial 
(https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/Getting_Caffe1_Models_for_Translation.ipynb)

I still get an error. It always happens after translating the last layer.

**Comment by sherifshehata** [comment]
@bwasti @aaronmarkham @harouwu 
To give your more info, here is the error showing the values type.

```
ValueError: Unknown argument type: key=values value=[0.11257877945899963, ..., 0.13431508839130402], value type=<class 'google.protobuf.internal.containers.RepeatedScalarFieldContainer'>
```

**Comment by sherifshehata** [comment]
Followed solution from issue #482 and problem is solved
