### ISSUE TITLE
script converting model from caffe to caffe2

### ISSUE THREAD

**Issue by jimmyoic** [facebookarchive/caffe2#455]
I want to convert the net which consists of several convolutional layers from caffe to caffe2.

Followed the tutorial, I got some error messages like the below:

Traceback (most recent call last):
 28   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 29     "__main__", fname, loader, pkg_name)
 30   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
 31     exec code in run_globals
 32   File "/home/jimmyoic/caffe2/caffe2/python/caffe_translator.py", line 612, in <module>
 33     init_net = ConvertTensorProtosToInitNet(pretrained_params, external_input)
 34   File "/home/jimmyoic/caffe2/caffe2/python/caffe_translator.py", line 150, in ConvertTensorProtosToInitNet
 35     utils.MakeArgument("values", tensor.float_data)])
 36   File "/home/jimmyoic/caffe2/caffe2/python/utils.py", line 101, in MakeArgument
 37     (key, str(value), str(type(value)))
ValueError: Unknown argument type: key=values value=[.............

with many floating numbers, which seems like the weight of my pre-trained model.

In the tutorial, it didn't mention anything we should be careful about.
The thing I have noticed is that this cannot be done with some layers which are not registered in the code (Silence, Slice ... e.t.c).

Any idea to solve the problem?
Thanks!

**Comment by xhsoldier** [comment]
I met the same error, any solutions?

**Comment by agarwal-ayushi** [comment]
You need to update the protobuf version by using this command:
sudo pip install --upgrade protobuf
After upgrading, re-make caffe2 and the issue will be solved.
