### ISSUE TITLE
fail happened when running demo "resnet50_trainer.py" on multiple machine

### ISSUE THREAD

**Issue by dacson** [facebookarchive/caffe2#500]
logs of running "python resnet50_trainer.py" as below:

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1499968
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU: 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
**WARNING:data_parallel_model:Distributed computed params all-reduce not implemented yet**
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Remapping 128 blobs, using 19 shared
INFO:memonger:Memonger memory optimization took 0.0103449821472 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU: 0
INFO:data_parallel_model:Parameter update function not defined --> only forward
Traceback (most recent call last):
  File "resnet50_trainer.py", line 395, in <module>
    main()
  File "resnet50_trainer.py", line 391, in main
    Train(args)
  File "resnet50_trainer.py", line 315, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/home/dl01/caffe2/build/caffe2/python/workspace.py", line 161, in RunNetOnce
    return C.run_net_once(StringifyProto(net))
RuntimeError: [enforce fail at file_store_handler.cc:132] false. Wait timeout for name(s): allreduce_0_cw_op/1/0 Error from operator: 
input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "rank" i: 0 } arg { name: "size" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"

ps :
   try to use redis and nfs ,  but all is same problem, but i found the  warning "data_parallel_model:Distributed computed params all-reduce not implemented yet", maybe related with  the error , 
 

the srouce code of "caffe2/caffe2/python/data_parallel_model.py " as below:

def _BroadcastComputedParamsDistributed(
    devices,
    model,
    rendezvous,
):
    _BroadcastComputedParamsSingleHost(devices, model)
    **log.warn("Distributed computed params all-reduce not implemented yet")**

**Comment by pietern** [comment]
Thanks for the report @dacson.

The real error here is `[enforce fail at file_store_handler.cc:132] false. Wait timeout for name(s)`. This means one of the nodes times out waiting for (one of) the other node(s). If you use the file store handler, you'll have to pass a path to a shared filesystem, otherwise the nodes will never be able to find each other.

What was the error when you tried using the Redis handler?

**Comment by dacson** [comment]
Thanks for you answer@pietern.
 I already found the reason for "time out" problem, due to hostname's setting is wrong.
But the still running fail, new problem occur for "redis" and "nfs"  two cases, the log as below:

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1499968
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU: 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed computed params all-reduce not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Remapping 128 blobs, using 19 shared
INFO:memonger:Memonger memory optimization took 0.0102641582489 secs
*** Aborted at 1493956530 (unix time) try "date -d @1493956530" if you are using GNU date ***
PC: @     0x7f59ba51b9c8 gloo::transport::tcp::CreateDevice()
*** SIGSEGV (@0x10) received by PID 26645 (TID 0x7f59c107f740) from PID 16; stack trace: ***
    @     0x7f59c0c78330 (unknown)
    @     0x7f59ba51b9c8 gloo::transport::tcp::CreateDevice()
    @     0x7f59b9840e1a _ZSt16__once_call_implISt12_Bind_simpleIFZN6caffe24gloo17CreateCommonWorldINS1_11CUDAContextEE12createDeviceEvEUlvE_vEEEvv
    @     0x7f59c0c75a80 __GI___pthread_once
    @     0x7f59b984192d _ZN6caffe210RegistererISsNS_12OperatorBaseEJRKNS_11OperatorDefEPNS_9WorkspaceEEE14DefaultCreatorINS_4gloo17CreateCommonWorldINS_11CUDAContextEEEEESt10unique_ptrIS1_St14default_deleteIS1_EES4_S6_
    @     0x7f59ba8b27cf std::_Function_handler<>::_M_invoke()
    @     0x7f59ba21cf95 caffe2::(anonymous namespace)::TryCreateOperator()
    @     0x7f59ba21d3d1 caffe2::CreateOperator()
    @     0x7f59ba20cead caffe2::SimpleNet::SimpleNet()
    @     0x7f59ba20d23f caffe2::CreateNet()
    @     0x7f59ba2136fc caffe2::Workspace::RunNetOnce()
    @     0x7f59ba8b0d8f _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE18_bIS8_EINS_4nameENS_7siblingENS_5scopeEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlPNS_6detail15function_recordENS_6handleESR_SR_E1_clESQ_SR_SR_SR_.isra.1406
    @     0x7f59ba8b0fc7 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE18_bIS8_EINS_4nameENS_7siblingENS_5scopeEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlPNS_6detail15function_recordENS_6handleESR_SR_E1_4_FUNESQ_SR_SR_SR_
    @     0x7f59ba8b9ab2 pybind11::cpp_function::dispatcher()
    @           0x523f6d (unknown)
    @           0x5247ea (unknown)
    @           0x555551 (unknown)
    @           0x525560 (unknown)
    @           0x555551 (unknown)
    @           0x525560 (unknown)
    @           0x567d14 (unknown)
    @           0x465bf4 (unknown)
    @           0x46612d (unknown)
    @           0x466d92 (unknown)
    @     0x7f59c08c1f45 (unknown)
    @           0x577c2e (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

PS :  Running parameter

def main():
    # TODO: use argv
    parser = argparse.ArgumentParser(
        description="Caffe2: Resnet-50 training"
    )
    parser.add_argument("--train_data", type=str, default='/mnt/sdb1/data/train_lmdb',
                        help="Path to training data or 'everstore_sampler'",
                        required=False)
    parser.add_argument("--test_data", type=str, default=None,
                        help="Path to test data")
    parser.add_argument("--db_type", type=str, default="lmdb",
                        help="Database type (such as lmdb or leveldb)")
    parser.add_argument("--gpus", type=str,
                        help="Comma separated list of GPU devices to use")
    parser.add_argument("--num_gpus", type=int, default=1,
                        help="Number of GPU devices (instead of --gpus)")
    parser.add_argument("--num_channels", type=int, default=3,
                        help="Number of color channels")
    parser.add_argument("--image_size", type=int, default=227,
                        help="Input image size (to crop to)")
    parser.add_argument("--num_labels", type=int, default=2,
                        help="Number of labels")
    parser.add_argument("--batch_size", type=int, default=32,
                        help="Batch size, total over all GPUs")
    parser.add_argument("--epoch_size", type=int, default=1500000,
                        help="Number of images/epoch, total over all machines")
    parser.add_argument("--num_epochs", type=int, default=1000,
                        help="Num epochs.")
    parser.add_argument("--base_learning_rate", type=float, default=0.1,
                        help="Initial learning rate.")
    parser.add_argument("--weight_decay", type=float, default=1e-4,
                        help="Weight decay (L2 regularization)")
    parser.add_argument("--cudnn_workspace_limit_mb", type=int, default=64,
                        help="CuDNN workspace limit in MBs")
    parser.add_argument("--num_shards", type=int, default=2,
                        help="Number of machines in distributed run")
    parser.add_argument("--shard_id", type=int, default=0,
                        help="Shard id.")
    parser.add_argument("--run_id", type=str, default='437',
                        help="Unique run identifier (e.g. uuid)")
    #parser.add_argument("--redis_host", type=str, default='172.25.34.12',
    #                    help="Host of Redis server (for rendezvous)")
    parser.add_argument("--redis_host", type=str, 
                        help="Host of Redis server (for rendezvous)")
    parser.add_argument("--redis_port", type=int, default=6379,
                        help="Port of Redis server (for rendezvous)")
    parser.add_argument("--file_store_path", type=str, default='/mnt/nfs-12',
                        help="Path to directory to use for rendezvous")
    args = parser.parse_args()

    Train(args)

if __name__ == '__main__':
    workspace.GlobalInit(['caffe2', '--caffe2_log_level=2'])
    main()

**Comment by pietern** [comment]
Wow, I haven't seen that one before! The segfault happens gloo::transport::tcp::CreateDevice. Could you rebuild Caffe2 with `-DCMAKE_BUILD_TYPE=Debug` and try running again? This will hopefully give us some more information about where exactly the crash is happening. Many thanks!

**Comment by dacson** [comment]
Thanks your analysis！
No problem, i will upload the debug info 's logs for you next monday,

**Comment by dacson** [comment]
@pietern , below is logs of debug version, please check again, thanks!

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1499968
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU: 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed computed params all-reduce not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Remapping 128 blobs, using 19 shared
INFO:memonger:Memonger memory optimization took 0.0105330944061 secs
*** Aborted at 1494218887 (unix time) try "date -d @1494218887" if you are using GNU date ***
PC: @     0x7f4f48847a31 gloo::transport::tcp::CreateDevice()
*** SIGSEGV (@0x0) received by PID 29113 (TID 0x7f4f4f859740) from PID 0; stack trace: ***
    @     0x7f4f4f452330 (unknown)
    @     0x7f4f48847a31 gloo::transport::tcp::CreateDevice()
    @     0x7f4f46e138a2 _ZZN6caffe24gloo17CreateCommonWorldINS_11CUDAContextEE12createDeviceEvENKUlvE_clEv
    @     0x7f4f46e13e7c _ZNSt12_Bind_simpleIFZN6caffe24gloo17CreateCommonWorldINS0_11CUDAContextEE12createDeviceEvEUlvE_vEE9_M_invokeIIEEEvSt12_Index_tupleIIXspT_EEE
    @     0x7f4f46e13dbf _ZNSt12_Bind_simpleIFZN6caffe24gloo17CreateCommonWorldINS0_11CUDAContextEE12createDeviceEvEUlvE_vEEclEv
    @     0x7f4f46e13c54 _ZSt16__once_call_implISt12_Bind_simpleIFZN6caffe24gloo17CreateCommonWorldINS1_11CUDAContextEE12createDeviceEvEUlvE_vEEEvv
    @     0x7f4f4f44fa80 __GI___pthread_once
    @     0x7f4f46e12d93 __gthread_once()
    @     0x7f4f46e13b39 _ZSt9call_onceIZN6caffe24gloo17CreateCommonWorldINS0_11CUDAContextEE12createDeviceEvEUlvE_JEEvRSt9once_flagOT_DpOT0_
    @     0x7f4f46e13a11 caffe2::gloo::CreateCommonWorld<>::createDevice()
    @     0x7f4f46e13707 caffe2::gloo::CreateCommonWorld<>::CreateCommonWorld()
    @     0x7f4f46e133ca caffe2::Registerer<>::DefaultCreator<>()
    @     0x7f4f4900d63a std::_Function_handler<>::_M_invoke()
    @     0x7f4f483519d0 std::function<>::operator()()
    @     0x7f4f4834f5da _ZN6caffe28RegistryISsNS_12OperatorBaseEJRKNS_11OperatorDefEPNS_9WorkspaceEEE6CreateERKSsS4_S6_
    @     0x7f4f4834a5fb caffe2::(anonymous namespace)::TryCreateOperator()
    @     0x7f4f4834ac38 caffe2::CreateOperator()
    @     0x7f4f48329bb2 caffe2::SimpleNet::SimpleNet()
    @     0x7f4f4832bc2c _ZN6caffe211make_uniqueINS_9SimpleNetEJRKNS_6NetDefERPNS_9WorkspaceEEEENSt9enable_ifIXntsrSt8is_arrayIT_E5valueESt10unique_ptrISA_St14default_deleteISA_EEE4typeEDpOT0_
    @     0x7f4f48329723 caffe2::CreateNet()
    @     0x7f4f48334a2c caffe2::Workspace::RunNetOnce()
    @     0x7f4f48fd29b0 _ZZN6caffe26python16addGlobalMethodsERN8pybind116moduleEENKUlRKNS1_5bytesEE18_clES6_
    @     0x7f4f48fed41a _ZN8pybind116detail11type_casterISt5tupleIIRKNS_5bytesEEEvE4callIbRZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlS5_E18_ILm0EEEET_OT0_NS0_14index_sequenceIIXspT1_EEEE
    @     0x7f4f48fec0a6 _ZN8pybind116detail11type_casterISt5tupleIIRKNS_5bytesEEEvE4callIbRZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlS5_E18_EENSt9enable_ifIXntsrSt7is_voidIT_E5valueESH_E4typeEOT0_
    @     0x7f4f48fe8524 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE18_bIS8_EINS_4nameENS_7siblingENS_5scopeEEEEvOT_PFT0_DpT1_EDpRKT2_ENKUlPNS_6detail15function_recordENS_6handleESR_SR_E1_clESQ_SR_SR_SR_
    @     0x7f4f48fe8620 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE18_bIS8_EINS_4nameENS_7siblingENS_5scopeEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlPNS_6detail15function_recordENS_6handleESR_SR_E1_4_FUNESQ_SR_SR_SR_
    @     0x7f4f48ff6a14 pybind11::cpp_function::dispatcher()
    @           0x523f6d (unknown)
    @           0x5247ea (unknown)
    @           0x555551 (unknown)
    @           0x525560 (unknown)
    @           0x555551 (unknown)
Segmentation fault (core dumped)

**Comment by Knight-X** [comment]
I run the same script and it also fail from different error message. (debug version)
OS: Ubuntu 16.04
gcc 5.4
cudnn: 6.0
cuda: 8.0
ThinkPad-T460
GeForce 940MX/PCIe/SSE2

python resnet50_trainer.py --train_data ../../python/tutorials/tutorial_data/mnist/mnist-train-nchw-leveldb/ --db_type leveldb


Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU: 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Remapping 128 blobs, using 19 shared
INFO:memonger:Memonger memory optimization took 0.00809907913208 secs
INFO:resnet50_trainer:Starting epoch 0/1000
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:398] error == cudaSuccess. 2 vs 0. Error at: /home/kazami/workspace/caffe2/caffe2/core/context_gpu.cu:398: out of memory Error from operator: 
input: "gpu_0/comp_0_sum_3" input: "gpu_0/comp_1_spatbn_3" output: "gpu_0/comp_1_sum_3" name: "" type: "Sum" device_option { device_type: 1 cuda_gpu_id: 0 }
*** Aborted at 1494389721 (unix time) try "date -d @1494389721" if you are using GNU date ***
PC: @     0x7fc6e1e98428 gsignal
*** SIGABRT (@0x3e800003e49) received by PID 15945 (TID 0x7fc6967fc700) from PID 15945; stack trace: ***
    @     0x7fc6e223d390 (unknown)
    @     0x7fc6e1e98428 gsignal
    @     0x7fc6e1e9a02a abort
    @     0x7fc6d41f784d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fc6d41f56b6 (unknown)
    @     0x7fc6d41f5701 std::terminate()
    @     0x7fc6d4220d38 (unknown)
    @     0x7fc6e22336ba start_thread
    @     0x7fc6e1f6982d clone
    @                0x0 (unknown)
Terminated (core dumped)

**Comment by githubgsq** [comment]
@dacson hello, dacson~ I met the same error as you mentioned above.
When I run distributed version resnet50_trainer.py with mpirun, "timeout" occured.
You said the error you encountered is due to wrong hostname's setting, so how did you altered the hostname? using IP address or other method? I used host IP but no effect.
could you share your opinions please? Thanks:)
