### ISSUE TITLE
How to solve No module named google.protobuf.internal 

### ISSUE THREAD

**Issue by ghost** [facebookarchive/caffe2#610]
when I run 
python -c 'from caffe2.python import core'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "caffe2/python/core.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2
  File "caffe2/proto/caffe2_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal

**Comment by szbach** [comment]
do you solve it now? i also got the same error...

**Comment by yabinzhangJohn** [comment]
I have encounter the similar problem.
I am using anaconda2, and my problem is that I have installed multiple protobuf (`conda install -c distributions libprotobuf=2.5.0`, which is used for caffe compilation , and also `pip install protobuf`, which is 3.3.0 mistakenly installed at first).
So I used `pip uninstall protobuf` and  successfully uninstalled protobuf-3.3.0, then the pycaffe import works.

**Comment by himanshuhkr** [comment]
I am too facing this issue. I have both anaconda2 and anaconda3 installed(i know its bad way to have both python version, but i had my own reasons.) I changed the makefile  to point to python2 anaconda and installed caffe2. Now I am facing the same issue. Any one can suggest what may be the problem?

**Comment by urudus** [comment]
I tried https://stackoverflow.com/questions/37666241/importing-caffe-results-in-importerror-no-module-named-google-protobuf-interna and it helps
