### ISSUE TITLE
installation issue on ubuntu server v14.04

### ISSUE THREAD

**Issue by szbach** [facebookarchive/caffe2#626]
# **Hi, everyone. I install caffe2 on ubuntu server v14.04 according the guide and the process of compiling is all right. However,something is wrong when i run the command:python -c 'from caffe2.python import core'**

_Traceback (most recent call last):
  File "/home/benson/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1062, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/benson/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1084, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/home/benson/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/benson/caffe2/build/caffe2/python/core.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2
  File "/home/benson/caffe2/build/caffe2/proto/caffe2_pb2.py", line 182, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "/home/benson/anaconda3/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 869, in _ParseOptions
    message.ParseFromString(string)
  File "/home/benson/anaconda3/lib/python3.5/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/home/benson/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1068, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message._

I've no idea to deal with it. Any help will be appreciated!

**Comment by szbach** [comment]
BTW, i used anaconda3 to install the python3.5 and other optional dependent packages...

**Comment by aaronmarkham** [comment]
> i used anaconda3 to install the python3.5
You need the 2.7 version of Python.

**Comment by szbach** [comment]
@aaronmarkham Many thanks... it works now when i use python v2.7 and i also find the version troubleshooting in the following link:
_https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile_
