### ISSUE TITLE
relu_op_test error

### ISSUE THREAD

**Issue by auroua** [facebookarchive/caffe2#681]
I have build caffe2 with no error.  But when I run some test I got the following.
How could I solve it?
```
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build$ python -m caffe2.python.operator_test.relu_op_test
段错误 (核心已转储)
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build$ python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
段错误 (核心已转储)
Failure

```

**Comment by Yangqing** [comment]
Is this still present in the most recent head version?

Can you run the binaries such as `speed_benchmark --help` without error?

**Comment by auroua** [comment]
@Yangqing 
I have built the most recent head version this afternoon. It still have errors. The following is the outputs.
```
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build$ python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Failure
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build$ python -m caffe2.python.operator_test.relu_op_test
Traceback (most recent call last):
  File "/usr/software/anaconda3/envs/python27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/software/anaconda3/envs/python27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aurora/workspaces/caffe2/build/caffe2/python/operator_test/relu_op_test.py", line 6, in <module>
    from caffe2.python import core
  File "caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ImportError: No module named past.builtins
```
I found it is the same as #712 .
I also tested the binaries ``` speed_benchmark --help``` and others binaries. All of them output the segmentation fault. The following is the outputs.
```
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build/caffe2/binaries/binaries$ ./speed_benchmark --help
段错误 (核心已转储)
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build/caffe2/binaries/binaries$ ./run_plan
段错误 (核心已转储)
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build/caffe2/binaries/binaries$ ./split_db 
段错误 (核心已转储)
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build/caffe2/binaries/binaries$ ./tutorial_blob 
段错误 (核心已转储)
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build/caffe2/binaries$ ./blob_gpu_test 
段错误 (核心已转储)
(python27) aurora@aurora-alienware:~/workspaces/caffe2/build/caffe2/binaries$ ./blob_test 
段错误 (核心已转储)
```

**Comment by matschm** [comment]
I have the same issue here.
Fresh clone on Ubuntu 16.04.

$ python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Failure
$ python -m caffe2.python.operator_test.relu_op_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/gigant/libs/caffe2/build/caffe2/python/operator_test/relu_op_test.py", line 6, in <module>
    from caffe2.python import core
  File "caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ImportError: No module named past.builtins

The binaries on the other side are working.
