### ISSUE TITLE
Caffe translation error: Deconvolution layer

### ISSUE THREAD

**Issue by ndcuong91** [facebookarchive/caffe2#753]
I'm running across the following error when i convert Resnet-101 model from Caffe to Caffe2:

"...
INFO:caffe_translator:Translate layer res5c
INFO:caffe_translator:Translate layer res5c_relu
INFO:caffe_translator:Translate layer res5c_up_pose
Traceback (most recent call last):
  File "/home/bs1/PycharmProjects/Caffe2/caffe_translator.py", line 715, in <module>
    net, pretrained_params = TranslateModel( caffenet, caffenet_pretrained, is_test=True)
  File "/home/bs1/PycharmProjects/Caffe2/caffe_translator.py", line 129, in TranslateModel
    return TranslatorRegistry.TranslateModel(*args, **kwargs)
  File "/home/bs1/PycharmProjects/Caffe2/caffe_translator.py", line 122, in TranslateModel
    layer, pretrained_blobs, is_test)
  File "/home/bs1/PycharmProjects/Caffe2/caffe_translator.py", line 67, in TranslateLayer
    layer, pretrained_blobs, is_test)
  File "/home/bs1/PycharmProjects/Caffe2/caffe_translator.py", line 310, in TranslateDeconv
    weight = utils.NumpyArrayToCaffe2Tensor(pretrained_blobs[0], output + '_w')
IndexError: list index out of range
"
When debug, i found that **pretrained_blobs** is an empty array
the reason is len(pretrained_layer)=0 (The comment say "no pretrained layer for the given layer name")
Anyone can help?

**Comment by lzx1413** [comment]
try to make sure whether the deconv layers has weights in caffe model

**Comment by ndcuong91** [comment]
@lzx1413  tks bro, i will try it

**Comment by wdx04** [comment]
I have the similar issue. I have some deconvolution layers with "bias_term: false" param, which are common in FCN-like nets for semantic segmentation. But the translation script ignores the "bias_term: false" param and try to convert the bias.

**Comment by Kowasaki** [comment]
I'm running into the same issue--what would be the best approach for "bias_term: false" ? Should I return a zero caffe2tensor for bias or is there some other way?

**Comment by wdx04** [comment]
Making an all-zero Caffe2Tensor seems to be the right way.
```python
if len(pretrained_blobs) > 1:
    bias = utils.NumpyArrayToCaffe2Tensor(pretrained_blobs[1].flatten(), output + '_b')
else:
    bias = utils.NumpyArrayToCaffe2Tensor(np.zeros(pretrained_blobs[0].shape[:1], dtype=np.float32).flatten(), output + '_b')
```
