### ISSUE TITLE
resnet50_trainer.py can only run 1 epoch of ImageNet training

### ISSUE THREAD

**Issue by hanyunfan** [facebookarchive/caffe2#889]
It can run, but only 1 epoch, at the end of epoch 0, it reports below error. This is run on single nodes with 4 P100. 

INFO:resnet50_trainer:Training loss: 3.44776368141, accuracy: 0.319999992847
INFO:resnet50_trainer:Finished iteration 3748/3750 of epoch 0 (547.22 images/sec)
INFO:resnet50_trainer:Training loss: 3.42598390579, accuracy: 0.34999999404
INFO:resnet50_trainer:Finished iteration 3749/3750 of epoch 0 (538.25 images/sec)
INFO:resnet50_trainer:Training loss: 2.95003175735, accuracy: 0.310000002384
INFO:resnet50_trainer:Finished iteration 3750/3750 of epoch 0 (554.19 images/sec)
INFO:resnet50_trainer:Training loss: 3.4275188446, accuracy: 0.310000002384
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cm/shared/apps/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 455, in <module>
    main()
  File "/cm/shared/apps/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 451, in main
    Train(args)
  File "/cm/shared/apps/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 388, in Train
    SaveModel(args, train_model, epoch)
  File "/cm/shared/apps/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 94, in SaveModel
    predictor_export_meta=predictor_export_meta,
  File "caffe2/python/predictor/predictor_exporter.py", line 177, in save_to_db
    serde.serialize_protobuf_struct(meta_net_def)
  File "caffe2/python/workspace.py", line 263, in FeedBlob
    return C.feed_blob(name, arr, StringifyProto(device_option))
RuntimeError: Unable to cast Python instance of type <type 'str'> to C++ type 'std::string''

And use below command to run it:

python -m caffe2.python.examples.resnet50_trainer --train_data /database/caffe/ilsvrc12_train_lmdb --test_data /database/caffe/ilsvrc12_val_lmdb --num_gpus 4 --batch_size 400 --num_epochs 2

tired different batch size, 256, 384, 400 all report the same error, and using the most updated code, download from git again today, still the same.

Thanks in advance.

**Comment by hanyunfan** [comment]
The above error message was generated in debug mode (-DCMAKE_BUILD_TYPE=Debug)

**Comment by pietern** [comment]
@hanyunfan I think I have seen something like this before. Can you share the CMake config summary?

I think this has to do with an out-of-tree pybind version being included rather than the bundled one. I recall seeing an Anaconda distribution including a newer version of pybind than supported by Caffe2. Compilation was fine, but it caused runtime errors like this one.

**Comment by pietern** [comment]
No activity on this issue, closing.
