### ISSUE TITLE
Resnet152 migration error

### ISSUE THREAD

**Issue by shinigami1392** [facebookarchive/caffe2#994]
When trying to migrate resnet152 from caffe to caffe2 getting following error: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pushkar/caffe2/build/caffe2/python/caffe_translator.py", line 713, in <module>
    caffenet, caffenet_pretrained, is_test=True
  File "/home/pushkar/caffe2/build/caffe2/python/caffe_translator.py", line 129, in TranslateModel
    return TranslatorRegistry.TranslateModel(*args, **kwargs)
  File "/home/pushkar/caffe2/build/caffe2/python/caffe_translator.py", line 122, in TranslateModel
    layer, pretrained_blobs, is_test)
  File "/home/pushkar/caffe2/build/caffe2/python/caffe_translator.py", line 70, in TranslateLayer
    str(layer))

KeyError: 'No translator registered for layer: name: "crop1"\ntype: "Crop"\nbottom: "res5c_up_pose"\nbottom: "res3d_pose"\ntop: "res5c_up_posec"\n yet.'

The prototxt and model can be found here:
https://github.com/eldar/deepcut-cnn/tree/master/models/deepercut

**Comment by leovandriel** [comment]
I was able to convert the ResNet152 model by making a few small adjustments to the model. Instructions and the resulting Caffe2 model can found here: [github.com/leonardvandriel/caffe2_models](https://github.com/leonardvandriel/caffe2_models#resnet)

**Comment by Mhugi** [comment]
@leonardvandriel  I've seen the suggested instructions - but how does it solve the crop problem?
